apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: linkding
    namespace: linkding
stringData:
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:hRlG75yJm1EFr9+1HwTkkea/xc1aYP1xhRYGk++HE44=,iv:yq9jIg+qP4OkJ/MJVl5WqBiCGlTtjGK/dtY4QYQzIEo=,tag:Citoofk3LX66hjIuVUcyHA==,type:str]
    OIDC_RP_CLIENT_SECRET: ENC[AES256_GCM,data:OWEdIDavhQtsAjWaWOKXVEAJnXMzJe1FcHNrsCF9MgnZeGbX/ZIP+t04iak=,iv:naELTFPT7rYh78yLJEwmoW0VEkGGvaG5udJEOmforSA=,tag:Ftr4mnpcHfXnSrpq3Sy3wQ==,type:str]
sops:
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVStkNkFOSkpsMGhnYjR3
            R05lV0Q4NjFKVmN0bEdXNEVwdTFXTitLajJJCmJoWkJMQm9vMGNkRGZwOU5icEMr
            SFUxbkpGSFh1YkNjcW13WEE5UklJRmsKLS0tIHEraEU5M2QvRHhqMkNQdmtWbDM5
            RG1pWWR2ZUkwemZoQ2RWeEU0TlpkeWcKThbnxatjL6XSt4fu0wjHFjhV8c3MDB70
            mR2R+CZUO6FWxFweKDg7YFylNdK09A+JpmTWn+0BdHU014OLxyaERw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-28T20:43:16Z"
    mac: ENC[AES256_GCM,data:4RV625kT2KkD8vIGaHOPjZP+QMSzis+vnW/iC2a78sJhiogWfSuL7RgzpOB5NRrCZKGU+E8Pmag8iYgpez9vlL2142qVfmT9yXtGHIpZ6nWPz9uattofusMihXYf/I+5t9yUsrpLe6m+ZmH2PLh52TKYVP3Qadv5zdr42LGk054=,iv:zx/hNiR3mUYcsRs23b430b/H5lYHbm6hNCvXukPrNZ4=,tag:aQrdK61ZnwJ7Rlx3CrrHDw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
