kind: Secret
ansible_user: ENC[AES256_GCM,data:VOliifSc2KA=,iv:iY9+9NoESTVgvF12tAoJdC4BuB1FTubNkVqu5bubwmY=,tag:TxsGN/lf7F9T9I2DDXs0wg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:luPNbTQ3,iv:/ZJjH8uyp5y8gnB2e/VLKzXH0GT0kfAfdoTHbJ0SjXQ=,tag:k1PjFInBPdTdDKb+JmLJhQ==,type:str]
mail: ENC[AES256_GCM,data:hyJjsOkYfThe5Rdkuf/ywNc=,iv:Rp1FmaNVnP48bypn+X/jpZpjBTKnLjjwbHAZfpVYzQc=,tag:jSNn+mS+yzr0X8PtyRnE7Q==,type:str]
plik_url: ENC[AES256_GCM,data:+15og91o+4v1D8nlar4pazlXXEm1jfug,iv:FDPfI/VG91B5b2Uzsr7LjYeLRgUEbs52aF14EA0wdw8=,tag:1CXZdZsf6YkMSAlfYnAoAw==,type:str]
plik_token: ENC[AES256_GCM,data:Tln/FR6fOcy2RKiFO3regUFjLYiAB7hWJSPXb3IqyjSclW3O,iv:cpGK7v+wqyfmF7S5JyhmR/yteBELkOQUSZh8CHmTX/s=,tag:c/TUSqXtgY2jgvA4OHhVfw==,type:str]
k3s_token: ENC[AES256_GCM,data:0x1keqdICnp9Z57NltsV8SPJZgXhQVUiknQbUHHj5cU3J2aRLbAWtXf5dmyMC2KPEMM9Hu3cg8Ik4fFTxChOdHusmFDzuHbm/OgTa8rQaeXExeGF1Cjt3jDBQ6BUlu+ITQyHw8ljmhzG6g1O,iv:oiMZfLQfdLSYZzrrqFo7Lv6+lIobPi3kMK43xtIQ1vc=,tag:bLevHtviOQLcRwIZkY0fhg==,type:str]
github_token: ENC[AES256_GCM,data:Kq2XAgZNwEps42iotrHaulqciXoPE1CGS1SWMg3ipNortHp7c9CExIRtVAEw3cSQoLsSwqD0mBcTW69b7C5dbtODqPDGRu/zVqEU53z2eHmYmRNEBgHqJ2QH+A5Q,iv:vvqUD1cetyzdgc1/D1bUtDq51tCtJ1jPmwgUAv7Fbfg=,tag:fvTT1HbShb50RXuwTHkTzA==,type:str]
chezmoi_name: ENC[AES256_GCM,data:95pU4b+LCwRBqWRbhJ22,iv:1bINDqWTFQ3eMOcXhemkJpW4L9lmyhFNb2D2HQO2iAc=,tag:sC2MKhfOegZ0UWjBuDM7vg==,type:str]
chezmoi_email: ENC[AES256_GCM,data:gHU61H9ko1yUY4u4791UKHslEe+ftE5I2Gs=,iv:CrTeecbU1YNDrz/rvsy85Z2QZWrJwsrlgYyPYvoIs88=,tag:lWhPNvsYunttn6zMCtL0Aw==,type:str]
chezmoi_email_github: ENC[AES256_GCM,data:EoXdTwzS9udw/zfvE2JRJkyyMS037s43,iv:hocsFRezHlXAMVyYJbZ1AjbFsCoZ/zXtfxeJBIQsJ7U=,tag:JDjxvEa8+K9066hqZtFj3g==,type:str]
chezmoi_age_key: ENC[AES256_GCM,data:i1hw0z+pDeSkZ7FBskbVGyCHXG0W2ryo4VfkY9Q9AAbI2HWIqLwK1b1k/e+4da48q0T4conC2Dsv63ZpvF/D1YWBSANuGWRxxCAjzelJIxs0JJGATas8Yb7MKi9it5QFRYE19GfZhu/Wk4pLZ9Lom0PJZdV7WPRu5KL7prm+bMD0BCh702khmG4bWcNfQUyy07mFTmNZrEWaLcow9g4gX2MQ47ILUZciv2ZuB7/ZFuhLVwbtVx2LUiekRT5y,iv:qmuKslFbu9sVFvjdEOwchQ5LesuUmwFkfdJbrpL/6S8=,tag:s+z5nHYRWdHKkQhr/0KxGw==,type:str]
sops:
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAweTFmcFRrd0g2Sk8yZXZC
            ZCs5WGF5cFVFbXErK1hrSFBZZkJOa1hCbUE0CjQzdGVrMHFvQnJ6Vk1kUXA3cXNM
            T0hEZUZJSndFdTVHMWlMY2hjRHJ3SEkKLS0tIGV5dk13QTVqcTZrNlB1cWhzUWJH
            TXkvOWlMc3pic1pkcDZsNlNScThVZ0kKlAJBUs92ywZft95AZO7Xmf97b7n5uEje
            igsPmvJy9gc+Qj5o3FM1MMkCZQAjXYEXgnGlKuyTqQNGPGskg/UTEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T15:11:33Z"
    mac: ENC[AES256_GCM,data:IjrikwFzyW6Nm70ubfBzgiirpzbvFGsdMQCSoRRBycBzi6NBFWBkKcYnPLZmv4XcC31liOV3GjNWRf+sRmmk6Eg9qJ9Kdk4tD2bK5alrYXEl/uOFqkKrraGMJp36W3htmE7H0jvAgFbPqSYRzbFBAyzIJALyiPfLMvIxYalGl8E=,iv:ZJqF48bHPxVk7yw3ljKQ7CQV2DUiV0HjNVLqflU474Q=,tag:vqJHc9n0RfiJWfiyKJbOMg==,type:str]
    unencrypted_regex: ^(kind)$
    version: 3.12.2
