kind: Secret
ansible_user: ENC[AES256_GCM,data:VOliifSc2KA=,iv:iY9+9NoESTVgvF12tAoJdC4BuB1FTubNkVqu5bubwmY=,tag:TxsGN/lf7F9T9I2DDXs0wg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:luPNbTQ3,iv:/ZJjH8uyp5y8gnB2e/VLKzXH0GT0kfAfdoTHbJ0SjXQ=,tag:k1PjFInBPdTdDKb+JmLJhQ==,type:str]
mail: ENC[AES256_GCM,data:hyJjsOkYfThe5Rdkuf/ywNc=,iv:Rp1FmaNVnP48bypn+X/jpZpjBTKnLjjwbHAZfpVYzQc=,tag:jSNn+mS+yzr0X8PtyRnE7Q==,type:str]
plik_url: ENC[AES256_GCM,data:+15og91o+4v1D8nlar4pazlXXEm1jfug,iv:FDPfI/VG91B5b2Uzsr7LjYeLRgUEbs52aF14EA0wdw8=,tag:1CXZdZsf6YkMSAlfYnAoAw==,type:str]
plik_token: ENC[AES256_GCM,data:Tln/FR6fOcy2RKiFO3regUFjLYiAB7hWJSPXb3IqyjSclW3O,iv:cpGK7v+wqyfmF7S5JyhmR/yteBELkOQUSZh8CHmTX/s=,tag:c/TUSqXtgY2jgvA4OHhVfw==,type:str]
k3s_token: ENC[AES256_GCM,data:0x1keqdICnp9Z57NltsV8SPJZgXhQVUiknQbUHHj5cU3J2aRLbAWtXf5dmyMC2KPEMM9Hu3cg8Ik4fFTxChOdHusmFDzuHbm/OgTa8rQaeXExeGF1Cjt3jDBQ6BUlu+ITQyHw8ljmhzG6g1O,iv:oiMZfLQfdLSYZzrrqFo7Lv6+lIobPi3kMK43xtIQ1vc=,tag:bLevHtviOQLcRwIZkY0fhg==,type:str]
github_token: ENC[AES256_GCM,data:Kq2XAgZNwEps42iotrHaulqciXoPE1CGS1SWMg3ipNortHp7c9CExIRtVAEw3cSQoLsSwqD0mBcTW69b7C5dbtODqPDGRu/zVqEU53z2eHmYmRNEBgHqJ2QH+A5Q,iv:vvqUD1cetyzdgc1/D1bUtDq51tCtJ1jPmwgUAv7Fbfg=,tag:fvTT1HbShb50RXuwTHkTzA==,type:str]
sops:
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAweTFmcFRrd0g2Sk8yZXZC
            ZCs5WGF5cFVFbXErK1hrSFBZZkJOa1hCbUE0CjQzdGVrMHFvQnJ6Vk1kUXA3cXNM
            T0hEZUZJSndFdTVHMWlMY2hjRHJ3SEkKLS0tIGV5dk13QTVqcTZrNlB1cWhzUWJH
            TXkvOWlMc3pic1pkcDZsNlNScThVZ0kKlAJBUs92ywZft95AZO7Xmf97b7n5uEje
            igsPmvJy9gc+Qj5o3FM1MMkCZQAjXYEXgnGlKuyTqQNGPGskg/UTEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T19:08:26Z"
    mac: ENC[AES256_GCM,data:U6bdJmEQIowLfvm5GVrDw0l5W/X3HUB3mLrQ70IQG8wNVz6fLkSDdOQZWSD7Yif9KkLuEZHVxn33AyI1F3LsSjB9LzXJ/O6D0iC2v+7xJWceKphxwYzi5Gr8JqRakIvUu9uI2X24O2aQbt4w28dUGIykZm5jgrFG1iCfBqBay8o=,iv:a0g5ND7Hm1CV02sB5nskVcnEfkgzH0MvDRu0iG+UGYw=,tag:VFKTzZI9MpUm7SAkhHW6EQ==,type:str]
    unencrypted_regex: ^(kind)$
    version: 3.12.2
