apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: dawarich-db
    namespace: dawarich
    annotations:
        reloader.stakater.com/match: "true"
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:a1d6f32VWGxeqCfloZbbXalnyzlgiinx9eN30OLEMbUGf67ICxayKVgIp30=,iv:okS1ENPZmC6gCL172SkUcBMVxDnYtKuDIN97aXFV2w8=,tag:eEQRhPGxRBIG8lKOlrI9FA==,type:str]
sops:
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVem93MU5UZDg1azlRYW5a
            QzNqNVZKVWhESXRaQ0hRMThWd3BMa2NqcEFzCisxNW04bklaRGJldURTN0NWYlpO
            eVhNdTZLVldwVTI4dWw0RGd5Z0pzZ2MKLS0tIG12TWxNL2lhQTNEZmp3Z1VpK3BD
            a1h5ZTJMNDloU1lTTnNKY1NBcEFNOTgK+cS8+hWI8TxB4siVz+12CFSoGeKFTvmV
            ncoWdPQ+BjUtjswBf7zRh8qQknCZGD0UzNIBkWieiAD4xJjKeryvdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-19T20:58:47Z"
    mac: ENC[AES256_GCM,data:JC7Zt2hmJzyGJR+wFFmnqIY7VUxaFHWrpM0gNavopbZ0+xq946yN5EKq/oBl0nUrpl10GMLtknywj1raHFjxhMgoMUTsbWLm3ieLG4+GYJyhtSVKGZMqJ71E15vL9a5IgDhjkGlryH5QkI/zRYIIRw/KhhgC00Mt8SvOwxJ+lio=,iv:vP2smYxc4szPP74HGDKYWbvvXrDTiJERTpcKNYIQgKc=,tag:3A3yn3X3D+Iw+Qiyc8VPSQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
