---
apiVersion: v1
kind: Service
metadata:
  name: dawarich-redis
  namespace: dawarich
spec:
  ports:
    - name: dawarich-redis
      port: 6379
      protocol: TCP
  selector:
    app.kubernetes.io/instance: dawarich-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dawarich-redis
  namespace: dawarich
  labels:
    app.kubernetes.io/instance: dawarich-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: dawarich-redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: dawarich-redis
    spec:
      restartPolicy: Always
      containers:
        - name: dawarich-redis
          image: redis:8.10-alpine
          command:
            - redis-server
            - "--save"
            - "900"
            - "1"
            - "--save"
            - "300"
            - "10"
            - "--appendonly"
            - "no"
          ports:
            - containerPort: 6379
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 5
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          emptyDir: {}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 80
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
