apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: dawarich
    namespace: dawarich
    annotations:
        reloader.stakater.com/match: "true"
stringData:
    SECRET_KEY_BASE: ENC[AES256_GCM,data:OH+HkEUJUfKTfLFHuWJwVeazgOsWtqP3MLwUYRblDZa50HwjgSHicb+MlG8l5y+Kwzz+qkRf+IsCZxUu4yyZtWWhT80GSH37JHdaKQkqYybOOPrNYTzOHbRendG7MIsSjca5uDao4wi7vn3Thb6NhE8TSi+d4ECG0RAtb+DjRKU=,iv:vN/sIFJl6mCU7Dr0JgpY5T0qPApSw9aqsqJwqD0KY3s=,tag:TQskPVZPOBWlEKbM4D2OwQ==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:c7vALBau1AAdGVeAcBib6wzrTd8fadjV4BbKEWKyprxvzdLA2qXiIoWZI0Q=,iv:7P+WIVt/qNZZHCZHVAYFdJmMGFm+iTGUbQvALZQGTFA=,tag:GDSWUX+yej4cAUxzgRJP1w==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:tRfp1OuQHEcbdFjpsmg/q58z73sORqcm46ZFPfTBmNmzAodwWmjh88QJhZfPGDzx5lZgKA0IX13Sj1eiS710vg==,iv:/IBvpLWhCTKT4XECip98Xb/tT4djBGT5DHum5z1L0Ek=,tag:Sw4jPUYPCtH1xzN1VlIeOA==,type:str]
sops:
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMUJSeUpDaVlDQkZQRndr
            U0xrVzg4TmdvdU5mNUNndi9OWGUvY3FaclJnCmhzT0xoOTNhSmFLN1E3MzYzTktU
            RHlJRTRGZmREUTNaMVRPVHUwT3d0KzAKLS0tIHJHbDAvMXZpNEF0K1NjTThycHl0
            WGZyR1FIWGVVdW5NTndSVG9Ua2RoN3cKiYy/IhuxBU90QYI3oO0MBUF/PFqrICey
            qU2YoATYVdDOdZXTIIKFIZOeeuOLOaJL0pgMcrlP8gNSrO4g/Zq5Cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-20T12:53:02Z"
    mac: ENC[AES256_GCM,data:9bF2p9rkW99uNxuRKeBcW3lay4qQhrF4+vlYGUhGVJK0+6PxWHBDH55Q0DJz//xMvRBEq0wVt6c51bar4zqS/HygVesbzWJbfstaqjuzMpS9VGFH9N+QbkFHtHdMqQmZyWsmBaK3A3dFtVZOHGUSf2IaKLmQxys57lvO0G34dSM=,iv:6A4DVbsUBmDAc0+9FR7JZwKSeLH5tD+9EdufW/Cmea8=,tag:ml2ylNg15CshXg346chOxg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
