---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dawarich-db
  namespace: dawarich
  annotations:
    reloader.stakater.com/match: "true"
data:
  POSTGRES_USER: dawarich
  POSTGRES_DB: dawarich
  PGDATA: "/var/lib/postgresql/data/pgdata"
---
apiVersion: v1
kind: Service
metadata:
  name: dawarich-db
  namespace: dawarich
spec:
  ports:
    - name: dawarich-db
      port: 5432
      protocol: TCP
  selector:
    app.kubernetes.io/instance: dawarich-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dawarich-db-pvc
  namespace: dawarich
spec:
  storageClassName: longhorn
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dawarich-db
  namespace: dawarich
  labels:
    app.kubernetes.io/instance: dawarich-db
  annotations:
    reloader.stakater.com/search: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: dawarich-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: dawarich-db
    spec:
      restartPolicy: Always
      containers:
        - name: dawarich-db
          image: postgis/postgis:17-3.5-alpine
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: dawarich-db
                optional: false
            - secretRef:
                name: dawarich-db
                optional: false
          ports:
            - containerPort: 5432
              name: dawarich-db
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - dawarich
                - -d
                - dawarich
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - dawarich
                - -d
                - dawarich
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 5
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: dawarich-db-vol
      volumes:
        - name: dawarich-db-vol
          persistentVolumeClaim:
            claimName: dawarich-db-pvc
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 80
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
