---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - dawarich-storage.yaml
  - dawarich-db.secret.sops.yaml
  - dawarich-db.yaml
  - dawarich-redis.yaml
  - dawarich.secret.sops.yaml
  - dawarich.yaml
