---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config-pvc
  namespace: media-automation
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: media-automation
  labels:
    app.kubernetes.io/instance: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: prowlarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: docker.io/linuxserver/prowlarr:2.3.5.5327-ls144
          ports:
            - containerPort: 9696
              name: http
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: {{TZ}}
          readinessProbe:
            httpGet:
              path: /ping
              port: 9696
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /ping
              port: 9696
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: prowlarr-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: media-automation
spec:
  ports:
    - port: 9696
      name: http
  selector:
    app.kubernetes.io/instance: prowlarr
