---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - nfs-pv.yaml
  - secret.sops.yaml
  - postgres.yaml
  - redis.yaml
  - collabora.yaml
  - nextcloud.yaml
