apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secrets
    namespace: nextcloud
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:/xdpThZ6I/laCnx/CNNgVdV7RYqaKWDfN1wG2SC2l9T/rb40JX2zRiP5ri4=,iv:JlGmpT295NFmStEbLi2Hw2VwpAmiYmRNFZW2EM6i3Ks=,tag:u9Zy8pqkUyTSh/j1HaYgTw==,type:str]
    NEXTCLOUD_ADMIN_USER: ENC[AES256_GCM,data:jxj1DjU=,iv:2IcIys5E2iXdR/dKZaJF8vDyjDF9MzvFGK0bKcLyaF4=,tag:+vSWOKTv2tiFyHf68JaGRA==,type:str]
    NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:IttY7qbxMHdCACKSgVbtF49jWx6UDGpK/8Kvneqzw101T8ERcNJY8tgyhGM=,iv:oe5obSWx5J0Yfer80ttWyn8qBiQFighV0cugviTiMBM=,tag:FHcUitadQndTuSm2b84HQw==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:3Khm0xlO7wl4/mjlqqmKrVk8b+8cwbW0X9dQtz4jUH+7wVC3eRx/1uBXlA4zcp/78AiH5/qBSyj03C0gVy+8zQ==,iv:czywpXQg0o2obS3pE2lrOjzL0ifns7yauTFmYBowNdA=,tag:bDChhFP07kyuNW7UXY7H/w==,type:str]
sops:
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaE5qRkJ0VXExT0doT2pX
            SG1EWEtBazI0VWhXclF0VzRpaFcxV2FyZW5NCmZTWDhzY2ZMR0ViUi8rYTFpUThv
            d0NGQWxDQVE1NW0rQWVIcVY3cEN6U2sKLS0tIGxZaEFEb0M1eW1pZVpTeFZLVlVF
            ZVhYbnEvSkJtaTllcThUYWJMMkk5QlUKHqwCGFE9ESfV+gu0St91HFxx94oONO82
            TnGaHJ+W7gYiwDI7zxgueji6vdkPbK/X1rdVSEH6zAK4PWLVC5vJ6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T08:38:17Z"
    mac: ENC[AES256_GCM,data:MfdAHP4E3xj44Z+NfTj3PY0f7jrvqs4PINK4STR+79u57BfUKU7qaJvNBHX/oEqmO3WVed09ElTCC3idhLt0z01ZLdOH7/euO/NTGywIuOXsLGuk9hjdYFhUXkpi928qh/XngY/vqQ+qEqrsTyNWAFyHff2X5OVymcCQRS6PPag=,iv:J1o9/PcbhRItNV1Ji5OPJVNBQVIq+qT4kD71s3WJU2E=,tag:snzsLC4oP9XeT1WiC027+w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
