apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secrets
    namespace: nextcloud
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:/xdpThZ6I/laCnx/CNNgVdV7RYqaKWDfN1wG2SC2l9T/rb40JX2zRiP5ri4=,iv:JlGmpT295NFmStEbLi2Hw2VwpAmiYmRNFZW2EM6i3Ks=,tag:u9Zy8pqkUyTSh/j1HaYgTw==,type:str]
    NEXTCLOUD_ADMIN_USER: ENC[AES256_GCM,data:jxj1DjU=,iv:2IcIys5E2iXdR/dKZaJF8vDyjDF9MzvFGK0bKcLyaF4=,tag:+vSWOKTv2tiFyHf68JaGRA==,type:str]
    NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:IttY7qbxMHdCACKSgVbtF49jWx6UDGpK/8Kvneqzw101T8ERcNJY8tgyhGM=,iv:oe5obSWx5J0Yfer80ttWyn8qBiQFighV0cugviTiMBM=,tag:FHcUitadQndTuSm2b84HQw==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:3Khm0xlO7wl4/mjlqqmKrVk8b+8cwbW0X9dQtz4jUH+7wVC3eRx/1uBXlA4zcp/78AiH5/qBSyj03C0gVy+8zQ==,iv:czywpXQg0o2obS3pE2lrOjzL0ifns7yauTFmYBowNdA=,tag:bDChhFP07kyuNW7UXY7H/w==,type:str]
    SMB_PASSWORD: ENC[AES256_GCM,data:zlEhGUJeqHIZNVquIMZ2mp527s0=,iv:/oG6XS1a9JK0tn5FPqTd8PukqvL6xVGSfQ09b/H2Gl8=,tag:6jfSu4W/px1gNOSlS5aPyg==,type:str]
sops:
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaE5qRkJ0VXExT0doT2pX
            SG1EWEtBazI0VWhXclF0VzRpaFcxV2FyZW5NCmZTWDhzY2ZMR0ViUi8rYTFpUThv
            d0NGQWxDQVE1NW0rQWVIcVY3cEN6U2sKLS0tIGxZaEFEb0M1eW1pZVpTeFZLVlVF
            ZVhYbnEvSkJtaTllcThUYWJMMkk5QlUKHqwCGFE9ESfV+gu0St91HFxx94oONO82
            TnGaHJ+W7gYiwDI7zxgueji6vdkPbK/X1rdVSEH6zAK4PWLVC5vJ6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T19:22:07Z"
    mac: ENC[AES256_GCM,data:tmrURwKHyQkQCF5pO7NnRjg5WSmqAiUkxHCj8yXXE9FGwRt1Jpp7Q8dZBzKRW1lsBVmKyRHxp8cH1E8cB5uQ0NilZ4HJ9Z/9+LLu+s5W0nBoBBDJoZGjNVKhRQKGXAuz1ROlI5zQo5u3gsF4L9XqThJRHzeE7hyJegaGHK2XVls=,iv:53+WDO20fWFihBS6CNxvW2VwpgY6d/cvXcS+VDt9aTA=,tag:pM1V3SCAyN5JHJWPC8NiTQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
