---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret.sops.yaml
  - plundrio
  - sonarr
  - radarr
  - seerr
  - prowlarr
  - calibre-web-automated
  - shelfmark
  - downloads-cleanup
