apiVersion: v1
kind: Secret
metadata:
    name: media-automation-secrets
    namespace: media-automation
stringData:
    PUTIO_TOKEN: ENC[AES256_GCM,data:W552eLplaK2ZrC+Lx3NH4elEtVM=,iv:oqE2ueU8RoWQLL1Hhe23KksZ2TQIW/7lv5qNAIjYWm4=,tag:rtir0rJKA/SRoaTlPZU4qA==,type:str]
sops:
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQa29CUnNHczF6dEdZUTV2
            Zm5jM3RBMHkrSW1pVjRBMDg5dE5TYTZhdEhrClBTZDlLU0Vla3RKNmlsZ29acVpQ
            aW5HaWNXNDBpN1pQOXdoYm5WZmhRWDQKLS0tIDJSVFRTMHpySk1SQngwcUdqMGV1
            bHJRdk4zbXBXR1lMdnpNQTZvcDRDOVEKN9g3VOm/cjYjmmHHx07JOEoAjXSZbiNu
            uKDP5xO/yXfHV2pdMPPWOLsbyjfb3JErOEtyU6MOq8oX0rRartT5YQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-28T20:16:26Z"
    mac: ENC[AES256_GCM,data:PFbQIet3J/AGECJHYDeNVmJ71zNLG5VdpSjfkc2hbcRXTnpD83WGCMW3+DNYSCM66XtlE9XVq9CtBq9AJAMqVJkRpnOo8RU6Ur9gw1u+gMAlEh4K2Nd2qD25e+e8jZshcjnhTl3PORiNZfHUF5EpJnbXJ0L8LKi2gvzxjolGx5o=,iv:JSAzBZR1KIkttaw5sgCeRh+QT/kQ7GDgO284w7sJSGI=,tag:TxJzmkmmXZE8ypX+Ik30QA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
