apiVersion: v1
kind: Secret
metadata:
    name: media-automation-secrets
    namespace: media-automation
stringData:
    PUTIO_TOKEN: ENC[AES256_GCM,data:W552eLplaK2ZrC+Lx3NH4elEtVM=,iv:oqE2ueU8RoWQLL1Hhe23KksZ2TQIW/7lv5qNAIjYWm4=,tag:rtir0rJKA/SRoaTlPZU4qA==,type:str]
sops:
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQa29CUnNHczF6dEdZUTV2
            Zm5jM3RBMHkrSW1pVjRBMDg5dE5TYTZhdEhrClBTZDlLU0Vla3RKNmlsZ29acVpQ
            aW5HaWNXNDBpN1pQOXdoYm5WZmhRWDQKLS0tIDJSVFRTMHpySk1SQngwcUdqMGV1
            bHJRdk4zbXBXR1lMdnpNQTZvcDRDOVEKN9g3VOm/cjYjmmHHx07JOEoAjXSZbiNu
            uKDP5xO/yXfHV2pdMPPWOLsbyjfb3JErOEtyU6MOq8oX0rRartT5YQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T08:53:15Z"
    mac: ENC[AES256_GCM,data:IQcmxR7AUuInCXm1d+CvQnSG+wQtIGh4aybJI6vKiMCbLfcXb6T5sgUuotLn2vxo15nxrvmkYz9TQvBfdvM3uF45qIhJsGb0AJEqXVxVWXELjgh+0uJZhXT9MDokWcmQ65rfv/OZhTDcHQQdRPVJJ59jEgRcO+jUOo2jJdqUkvQ=,iv:FEoeNjPvyBHfToWVaPQzvvY07mMxvwcwLdWE2Sd22Bo=,tag:r1AY1AEOci/FjdlulfsKRA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
