apiVersion: v1
kind: Secret
metadata:
    name: media-automation-secrets
    namespace: media-automation
stringData:
    PUTIO_TOKEN: ENC[AES256_GCM,data:W552eLplaK2ZrC+Lx3NH4elEtVM=,iv:oqE2ueU8RoWQLL1Hhe23KksZ2TQIW/7lv5qNAIjYWm4=,tag:rtir0rJKA/SRoaTlPZU4qA==,type:str]
    SHELFMARK_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:wg2ZLyp+iKKvmoCRtkWmOZ7tW5T0LS6khPe01Z+H4XI0Uj8qGO8pga+Iqh4=,iv:pxVsYclWAFQWl5if25f4z8cyz5K/LwfMUlkH+m7uqiY=,tag:E+psRXRbGk5Z528iulcpVw==,type:str]
sops:
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQa29CUnNHczF6dEdZUTV2
            Zm5jM3RBMHkrSW1pVjRBMDg5dE5TYTZhdEhrClBTZDlLU0Vla3RKNmlsZ29acVpQ
            aW5HaWNXNDBpN1pQOXdoYm5WZmhRWDQKLS0tIDJSVFRTMHpySk1SQngwcUdqMGV1
            bHJRdk4zbXBXR1lMdnpNQTZvcDRDOVEKN9g3VOm/cjYjmmHHx07JOEoAjXSZbiNu
            uKDP5xO/yXfHV2pdMPPWOLsbyjfb3JErOEtyU6MOq8oX0rRartT5YQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T13:02:59Z"
    mac: ENC[AES256_GCM,data:wKwriJFrZecvQIQYXF3sgy09z543BYEqQP+tL0IBnzx6sy8MONfgbruzqQT+d26x0s0ZSW71WeT61Oewy/sHPci8uLDmA9luExvOnN/h8o5JGS+wIVPl8WecfXUSF17ghGPb2gt32jVwXHZjClVoHFHdcqEJjZEcEz8PYb+QuiE=,iv:5TRgoF601jHFIf6dPg89YyT7EPLG9/YHnSinPmYZzfI=,tag:Tm9/NDsYLgD2s5J9P1O7zQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
