---
server:
  retentionPeriod: 7d
  persistentVolume:
    enabled: true
    storageClassName: longhorn
    size: 10Gi
  resources:
    requests:
      cpu: 600m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 1536Mi
  extraArgs:
    envflag.enable: "true"
    envflag.prefix: VM_
    loggerFormat: json
    search.maxConcurrentRequests: "8"
    search.maxQueueDuration: "30s"
