apiVersion: v1
kind: Secret
metadata:
    name: donetick
    namespace: donetick
stringData:
    DT_JWT_SECRET: ENC[AES256_GCM,data:c20Zvl+2ho7PoErtVUhC0qYQeJ/efs/3fJPEo6wyGWPyTUHeVj8GH+SZ4Qy8r+bybtTKcfoT0rqzV4OLNi2zGA==,iv:/2wR+TjFWmtTMLIEK9Wah0oeH3kMxfdtBuppjt3vWy0=,tag:tTSPKaoXpMDqUanyvbrQhQ==,type:str]
sops:
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNnl0SXNOem9YQmVxSGhM
            MXBTZnhkYmVmMFVXdFEwS0hxQnFDWGdaTERvCjIzMWkweHlDY3pPazZWNXJwWDRi
            dXdud2YzM2twL3hQMWhOSnpPNE4wbzQKLS0tIHV5RTFGbkQxTUNwV3krbmJqUnRo
            VmdhcUkrYkdjRVdFaW1pak5iNDdsNjAKTjqMu5Aiq68q+8WCKeZF4kkjjBWOShq2
            HEELy+ZAaOy5NHxL/C65/0ik0gQHNw+s1lfkJnLLbIrDy7reNjHUuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-26T19:57:34Z"
    mac: ENC[AES256_GCM,data:qbZT3847RMqFJwGeB0od0YD+NehPbSC7JAHCesr+UG/M0RHStCJL6kWFw0SSb9m+l/MtQpz/OqnsxttWxntyZ+DGbzVXIrwCBx905Er1kcrDCW0hjTb+L7ewovIoWzzTEVofH35dRdMJOostPYqM3aAyzsIIrljVC8w7zpmRlKY=,iv:tncBkPqmm21Ai0nbw+n/zKD1f5OCJEeFeaJjkIJZye8=,tag:Av2cGuJQCRNLOA2CEUamNg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
