---
- name: Download plik client binary arm64
  ansible.builtin.get_url:
    url: "https://github.com/root-gg/plik/releases/download/{{ plik_version }}/plik-{{ plik_version }}-linux-arm64"
    dest: /usr/local/bin/plik
    mode: '0755'
