---
- name: Create users accounts
  ansible.builtin.user:
    name: "{{ item.username }}"
    comment: "{{ item.comment }}"
    shell: /bin/zsh
    password: "{{ item.password }}"
    append: yes
    group: "{{ item.group }}"
    groups: "{{ item.groups }}"
    uid: "{{ item.uid }}"
    update_password: on_create
  with_items: "{{ users }}"

- name: Install chezmoi
  ansible.builtin.get_url:
    url: "https://github.com/twpayne/chezmoi/releases/latest/download/chezmoi-linux-{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
    dest: /usr/local/bin/chezmoi
    mode: '0755'

- name: Create chezmoi config directory
  ansible.builtin.file:
    path: /home/jlejeune/.config/chezmoi
    state: directory
    owner: jlejeune
    group: users
    mode: '0755'

- name: Create chezmoi config
  ansible.builtin.copy:
    dest: /home/jlejeune/.config/chezmoi/chezmoi.toml
    owner: jlejeune
    group: users
    mode: '0600'
    content: |
      [data]
          is_server = true

- name: Init and apply chezmoi dotfiles
  ansible.builtin.command:
    cmd: "chezmoi init --apply https://oauth2:{{ github_token }}@github.com/jlejeune/dotfiles.git"
    creates: /home/jlejeune/.local/share/chezmoi
  become: yes
  become_user: jlejeune
  environment:
    HOME: /home/jlejeune

- name: Remove the user 'pi'
  ansible.builtin.user:
    name: pi
    state: absent
    remove: yes
