---
- name: Create users accounts
  ansible.builtin.user:
    name: "{{ item.username }}"
    comment: "{{ item.comment }}"
    shell: /bin/zsh
    password: "{{ item.password }}"
    append: yes
    group: "{{ item.group }}"
    groups: "{{ item.groups }}"
    uid: "{{ item.uid }}"
    update_password: on_create
  with_items: "{{ users }}"

- name: Get latest chezmoi version
  ansible.builtin.uri:
    url: https://api.github.com/repos/twpayne/chezmoi/releases/latest
    return_content: true
  register: chezmoi_release
  delegate_to: localhost

- name: Install chezmoi from .tar.gz
  vars:
    chezmoi_version: "{{ chezmoi_release.json.tag_name | regex_replace('^v', '') }}"
    chezmoi_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
  ansible.builtin.unarchive:
    src: "https://github.com/twpayne/chezmoi/releases/download/v{{ chezmoi_version }}/chezmoi_{{ chezmoi_version }}_linux_{{ chezmoi_arch }}.tar.gz"
    dest: /usr/local/bin
    remote_src: false
    extra_opts:
      - chezmoi
    creates: /usr/local/bin/chezmoi

- name: Create chezmoi config directory
  ansible.builtin.file:
    path: /home/jlejeune/.config/chezmoi
    state: directory
    owner: jlejeune
    group: users
    mode: '0755'

- name: Create chezmoi config
  ansible.builtin.copy:
    dest: /home/jlejeune/.config/chezmoi/chezmoi.toml
    owner: jlejeune
    group: users
    mode: '0600'
    content: |
      [data]
          is_server = true

- name: Init and apply chezmoi dotfiles
  ansible.builtin.command:
    cmd: "chezmoi init --apply https://oauth2:{{ github_token }}@github.com/jlejeune/dotfiles.git"
    creates: /home/jlejeune/.local/share/chezmoi
  become: yes
  become_user: jlejeune
  environment:
    HOME: /home/jlejeune

- name: Remove the user 'pi'
  ansible.builtin.user:
    name: pi
    state: absent
    remove: yes
