---
vars:
  - targetPath: NAS_ADDRESS
    clusterConfigMap:
      name: cluster-settings
      namespace: default
      key: NAS_ADDRESS

deployments:
  - path: snapshot-controller
  - barrier: true
  - path: nfs-provisioner
  - path: longhorn
