---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-supabase-functions
  namespace: supabase
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  template:
    spec:
      containers:
        - name: supabase-functions
          env:
            - name: FCM_SERVICE_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: supabase
                  key: fcm_service_account
          volumeMounts:
            - name: edge-functions-convocation
              mountPath: /home/deno/functions/send-convocation-notification/index.ts
              subPath: index.ts
            - name: edge-functions-import-championship-matches
              mountPath: /home/deno/functions/import-group-results/index.ts
              subPath: index.ts
      volumes:
        - name: edge-functions-convocation
          configMap:
            name: supabase-edge-functions-send-convocation-notification
        - name: edge-functions-import-championship-matches
          configMap:
            name: supabase-edge-functions-import-championship-matches
