---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret.sops.yaml
  - helm-rendered.yaml
  - edge-functions-configmap.yaml
patches:
  - target:
      kind: Deployment
      labelSelector: app.kubernetes.io/instance=supabase
    patch: '[{"op": "add", "path": "/spec/strategy", "value": {"type": "Recreate"}}]'
  - path: functions-patch.yaml
    target:
      kind: Deployment
      name: supabase-supabase-functions
    options:
      allowNameChange: false
  - target:
      kind: StatefulSet
      labelSelector: app.kubernetes.io/instance=supabase
    patch: '[{"op": "add", "path": "/spec/updateStrategy", "value": {"type": "OnDelete"}}]'
    options:
      allowNameChange: false
