apiVersion: v1
kind: Secret
metadata:
    name: supabase
    namespace: supabase
type: Opaque
stringData:
    secret: ENC[AES256_GCM,data:8J+PPbJMhM6f/PTUSyNeoAL9ZVx3ptLL1CwC296fxQsuSrXmkfUHHUANFgM=,iv:jS0pA/SHRTZj+MpEDOShgBuSe/PfKMJ0GCV03TZ1Kec=,tag:Win6Iv0VrU80bmzf4qWESQ==,type:str]
    password: ENC[AES256_GCM,data:vPxoEpJvnFqicQhMzoaTj1yZ2hchc2Cjg3IhIdUcYJx0S9xpiTcieUUIo4aPH64o,iv:0YjdMSfmvmXcFjamplYzCROER5serHtw+fgdAfajmwU=,tag:/nrnTNd6x6bMHoEAMWpRdQ==,type:str]
    anonKey: ENC[AES256_GCM,data:yHO9C/ZR3DXxGDaWtDKKljuXmIwpi+ugqMRIQzJ7wXh1iYT0VQnEEAG1z36P/KL2MZ2q3WQOT+nKG1FazGi28+hte6M0jjvbRlzV1VqEeFrI/huyct1RPcxSJlWaMcf1QISPbc+jwG3FBKzckwtz+DqEo/H3NY+3vVGR0uD/dHF170eDIWpjpHuNEoWBTOcC7MUjctETXKeTb27X377XYQz1Z4oRB8fCKA==,iv:VtKGd5R8dKV4f4Co0gowDXZuXCXAwToml6NdHh8oA6A=,tag:OvJJi3m2kpmg5xd/RbI0MA==,type:str]
    serviceKey: ENC[AES256_GCM,data:V2R5mh+b6dUw14ND0L9XlwNxt5V/bjTY3Hcyve24ZYytkPmrr3A0FPWTCPLHOU+VKd367aOVwwPv4MnhkFufJoDUxXykjM2uAmJAm2qwiWBSdXpek2l5pGDOxVbd5uQWvp7Z9RIoZmEwOPUJBL03D7D5PeA/M63VZEoz1W/9vOS0MUO6Hqz2REVFyEvTJkUMM1ShetcaDWiFSBW1iTKXFHCBgAdlWo4AghLoQb0bpbVuWGzn,iv:SOplDcA7eKsU/zUz/SVnxs0gtpqBrMeKsoHHzu90NIk=,tag:rjc7A0m/dpM6MLejtxT/WQ==,type:str]
    database: ENC[AES256_GCM,data:mtqFmTfHl4o=,iv:e/q474OmwvJg+3rMa2ycHA0Ixndj4SGVNn2lB95wRso=,tag:7j+4j70rfH9e1rVZDbL42w==,type:str]
    dashboard_username: ENC[AES256_GCM,data:p+O1OBks4Wg=,iv:M4+WwJlbG+mXkhBoZLM+5yC3aNyXN9UlVOy+FPoD4hA=,tag:BhVHaXvkBXtd1EtDz4aoHw==,type:str]
    dashboard_password: ENC[AES256_GCM,data:MzJmHwOPuvBjQoedPDpB2/LOLZWziQ2QO0q/Hsf+t0Y=,iv:g7XnaawW2zfERkCoF9HW7xpg2CVFoMdL/+a8TZGQMV0=,tag:KPn1Nt20xD+/hwIwRBCxCg==,type:str]
    openAiApiKey: null
sops:
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZczRrL0xrRHAzZnNZNTJu
            ZGNRYi9zaTlZRThHL29DWERUbGJPNDRsbzJVCjlKNnJCNzhldXlENVVUa0VnSE9S
            dm9DWHpySnk4QVYxQnJNamhnSUZhQ0kKLS0tIDI3b3JvVEZmckNiWjk1ck1lS0lV
            OWw3OGVVaDhYSkpBT09VUFowSkxLTjAKBrO65iKZWROUrh7cirIMtB7Px2NEYwdn
            3zVxAt08YfnpHgzvaAwoFa0uuasvTAhMaOOKqHZAVpdFQjeZ+taf3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T20:23:10Z"
    mac: ENC[AES256_GCM,data:/WoJyklwwp5pIFHUc5lBqiPLQDFSjxeT1/C6aXhvx1dK6+Cm8zM2NAWqr/NB8nkkQmyd/fUDNvHvry53dirGN1XTTgf1QA0UFocniS0aIph+l1iVhQrd2AH/yopwcD2MmADTY5K8TTktiOOflPhnTf/O5NJKZmwAzf/xVuXq5Bs=,iv:rO6aQvXNzvmG4sDKMxCIr5a7zLsWBJwPaVnWsV48Foc=,tag:Wi2W2wbp75Mhb39xj5lfmQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
