apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_EMAIL: ENC[AES256_GCM,data:CNfNYJs7+Fbc3HWjo7OothR5VahruslR1ec=,iv:noONPO3CpSuIcdbVpu6W7hXo2FF8tMs02jrVgO5kE/E=,tag:Rl66QUf+9aSAkgV0Y9Ftug==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:ByqfNL2Tx+Tev7s=,iv:D35VM0iJOIy1NcPr4Hb2a2yAreKhDyLLG3vww5HvqEc=,tag:i3U72IvkZtcMkkNI9ZH7eQ==,type:str]
    SECRET_DYNAMIC_DOMAIN: ENC[AES256_GCM,data:kYiVoZrq/ANUFDV5SxM=,iv:GTEp+t8HAMmxLmtiYH3bcqAq7vgCe+bHBRgoT2mfFSY=,tag:2X0BUkpCdy2G9wbjTeEp8g==,type:str]
    SECRET_SMTP_HOST: ENC[AES256_GCM,data:eH50XYWZcRlxI1haxD/WgQ==,iv:/atN79LqeYAWE0e36aXZDI2DPt2UXT8XMNPZ7LnknOY=,tag:Omqtn5MZ9bie7Rws/C01pw==,type:str]
    SECRET_SMTP_USERNAME: ENC[AES256_GCM,data:LBF7I0r7CySiVYOAqQ63i3U=,iv:s6VNeUrR+8R5jKg8SKiw6OTy39RL1ww7nC+veAVcJJM=,tag:sOGG9MbW7wewotcS5duLuA==,type:str]
    SECRET_SMTP_PASSWORD: ENC[AES256_GCM,data:ZQxZIg8SbXtdqHuvP0tBlE6VinI=,iv:VZPhF5LvakzjAfoH4KTJv6lAm+PdVcPpATeIuAvPJU4=,tag:hn5CckF9JMdZrkzagYAiVA==,type:str]
    SECRET_JOPLIN_NOREPLY_EMAIL: ENC[AES256_GCM,data:5AJfeD8CBusJwboPATXJnQ3f7Qm7F3v1,iv:Q5aLLX7l/I1WZvp8ljZdFXO0nMg8BTi96pw+8aetPXA=,tag:vlBxxcAQVm4HcFJgaytFfQ==,type:str]
    SECRET_MEALIE_FROM_EMAIL: ENC[AES256_GCM,data:ZTwjoxgy1c7NBLaDRZRMQKjePCvYR1MZ,iv:AY5rQKU69tclOPPlLk9rVVSRB7s/3j9VPufWrMh4b3g=,tag:E2cEAk9sxeU1SahQ4l+/gA==,type:str]
    SECRET_LDAP_ADMIN_BIND_DN: ENC[AES256_GCM,data:gVnCbuBzeuDLuESik7EnRyickvSU4a2IxE9fAQ==,iv:6p5PREgdoslKklvhUJr4AOYYz61LsywmPxnbujduzss=,tag:DHx/KtbNPyOyslf22kbL7w==,type:str]
    SECRET_LDAP_ADMIN_QUERY_PASSWORD: ENC[AES256_GCM,data:stj1oLccDQ6Y/7mCfuD8eYi1ko4=,iv:BWA3g7D28kvOiuVzphdv43SHq/f4x81IW3LDiIsDmeM=,tag:wd0/LmA0Oa2EtZaWG1x8oQ==,type:str]
    SECRET_AUTHELIA_SENDER_EMAIL: ENC[AES256_GCM,data:Aiz7XJZdowaL5EW2gk040PN+JCy/01CDCjttrmmnbnAmO721UIJG29YcE0anJZ7EMocC9CeSn1EJ9kg=,iv:3tdFTp2BARyldfoh+xtE2zgsRumU/89COTj0uJFPl/M=,tag:LNbbU7/ezJHHg/gI8MB81g==,type:str]
    SECRET_IMMICH_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:47kvvSqsvV2g6Q6ILzceYDaVIe/AEpNQZmHN+jWFbyyoR9+D/Dw1+IHeBuPdChFmURtcZ/Php5C+NMbnSd6eix41yH/yNLJQWEPKnvOH+mTjBrdVnEI69eNW561x20zwhQ==,iv:j/bbTn53BzoRBHAP/okkyc7cK88AHKzJT5LQMLCnpr0=,tag:IIk2JMVHM9QtHcRuijoqnw==,type:str]
    SECRET_CAMERA_PASSWORD: ENC[AES256_GCM,data:/ifmMwJrR7VxPWMlBGVMFhys,iv:+f02nDVBPvHoFT6Lw2SKd7fbc9nvNThAwahXl7Hy4/c=,tag:5RaWFsQg7FE+D9f6OXQHew==,type:str]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:99Fc6ZDnKTB2Ke/+vnOs0oPSxNJarXoR9Nu7iHKeM3GSAFY5IEFWPlO5EWuqwEa/dStYpLyZzckMXaoiPywPkRaMQjpKjw380lyOUu0ISzp/pHOlZhr4L2U8gpm8rv5XSBese8DwVzZkWwtLq/mNbLdmp8UWzUlopw==,iv:Zviaw7LzXGbdwcQ2D/k+Nr6WnbAYohublGFD5M17Ncc=,tag:MvPc6P1tSed1g0mjgK3ZGQ==,type:str]
    SECRET_DAWARICH_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:XucGdRU/9x364y9TxeNp+NmZPlU69ClY00kIHd/G+VhgBHgDhxItAqXdwwcKrhXCEh42rZgBBwJmp11MEDNCfw==,iv:JLXpHSJuMdUx1PnFbnfZVgFs7sclOXDM/cNDtbBUTtg=,tag:2IYWJW3IplB/80yGXUB7aA==,type:str]
    SECRET_YAMTRACK_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:GoOBsyJFI8RPmVomgVkZRlNI2/sJTlbADSU5dUeitpUdQEbeDhJJ4zbxFX8wxg71kNATRydi2wFqzJsWyJCtRg==,iv:0YMsdsinLp8rvS1QpvAYCDO8x+yCS0IaLzTSR18bkxo=,tag:NUMnY+aQyioQnq0P6Q+upQ==,type:str]
    SECRET_FLOPPY_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:Xtga5TJpTN8KdC2fe1/6OG3D3ia6mZ1kliflfZt0DhdajRNWohYD5PkLJWFC4CgiiUKjWeqa3+2IC0/yWksHZw==,iv:QNVZrqOEhVJ3tsbeDlH1tkOpdn9O8vMfdUmvR34D8ts=,tag:aVRVAmmjUDcSPRYLCyAIdg==,type:str]
    SECRET_LINKDING_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:Yd4sQdej9vm/5JwlfnmNSxDKvI3+X3be5vqhMUHQYF0hT+WUA7/PAKXxxx8=,iv:9bAGNAJSzJI5pstKyLCCo/R2XgCXmIDuIWbbOriGviE=,tag:kd9+JYwJJVBd0uirSuwA4Q==,type:str]
sops:
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYWZnTG1KV3EzemRPbTA5
            ekMwejhRcUJCQUlkNUR0VnA2dzJJbXNGcDI4CjduVGhtVVNzNlFDeXFBaTRycDNo
            WnYvSTJaSDhBWG1wT0hsZUg5VE9MZk0KLS0tIDhENGhid2NRdzZVbFp4QkhGK09x
            K1p1bE5IMG11L3JmU0tZWGNIeFdHYlkKS32NpBdukeBIW5c3DtZW+3Ba4CjCJpkC
            GIlu7sppWW3Ad25sxO6QenvcJMBOmg5ZfLMo1ojWWOvljxjOTB+CXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-28T20:44:30Z"
    mac: ENC[AES256_GCM,data:sKwoKDFZqdukcGy2SwJz+NNj4FvWLKKV7ktNzirudwPeWMGfEkafxOYex4Ptg6/uVDZXBbxIwTrb4yRV82q2I7YVC+o1SV6JxdXVZikt8/3Gah4PgsHV2wWE2SUcG4yk28AFn4k6v5rZvNuAq8bfu8ESZhZKJzsbYTjQl/XVIdM=,iv:l0d5x8xL9WA2f0hMBxlx1rNftolHEWjjrHT4FQtimK0=,tag:A2vf9B1rHqlv6updMGqPvQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
