apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_EMAIL: ENC[AES256_GCM,data:nkOJsrTj0md6rk6bjbsdnMFFocK4yHpdBAU=,iv:oUIUOY+13XoOABoFlhHA2R51GwA4fZolwEsnYqtfHbI=,tag:XwMoh6aFvEVX/NL3HFPNpg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:n7PIIBKN5w14ooY=,iv:IC5CG81j4rSrkHBsOQmtNZA6RXoeIQX9dUbIF2BpLZo=,tag:3L13vtJdkQtQh8Z0ONT3EQ==,type:str]
    SECRET_DYNAMIC_DOMAIN: ENC[AES256_GCM,data:BR4jn4IDKkjR/F0sRzw=,iv:vitvtXFHumlK6O6WvJOQjlP311D8jaUrj74CIy0uP4Q=,tag:kYN2+K6fMl+UgJH00+79Qw==,type:str]
    SECRET_SMTP_HOST: ENC[AES256_GCM,data:Sn7vbJAYnrTwxYDtO57CKA==,iv:kjHAL6uO40S50SKUE6i6pmvK/m4l3eQxj4Z5rA4+bEo=,tag:NWA4o6SI636L6qS5HS+kFA==,type:str]
    SECRET_SMTP_USERNAME: ENC[AES256_GCM,data:xB+SAmqvotjReygh6cvcwBc=,iv:PluWrcTslNkNeV6nQdgJ77ELCh9TMIwDOdbIb8bFGbQ=,tag:nac5sjzkqDVxjdpwATEBlQ==,type:str]
    SECRET_SMTP_PASSWORD: ENC[AES256_GCM,data:+5cLBx/WOkJG0uM8dqgXaOUFwXE=,iv:i88RBl8B/4vLbcdVaFoSfRXSWRJNp7EDueQgcz7wOMM=,tag:1Fa5QmbU4sFHq53FwPibkQ==,type:str]
    SECRET_JOPLIN_NOREPLY_EMAIL: ENC[AES256_GCM,data:Vz1FkDrvuxlR/jT/L63AN7gLDyQS/D1J,iv:TtZ4lkPJoVO+947CvV8rchemOyE3l2TNw1RGWk11USI=,tag:IvChPAVqQYeYyS0V3rf3iA==,type:str]
    SECRET_MEALIE_FROM_EMAIL: ENC[AES256_GCM,data:T3b+CKHXvRsPUy0YJOA9BnFct7V6jybB,iv:AgkLnD9tIHMr8X1cUoFkr295OR1TQ5LKSZ+LM7ouXZI=,tag:p0etHzAX5cdZGWC+/LRhGA==,type:str]
    SECRET_LDAP_ADMIN_BIND_DN: ENC[AES256_GCM,data:HixPNLtIih1Rx3kg92HBChhvrahgcoqBS4yisQ==,iv:D1IDtK2ez6wjPjNXrrDEZkVyGAy1cns1rAkRbwN+Qh0=,tag:UyKpilpnhLtkHpFop0OUEg==,type:str]
    SECRET_LDAP_ADMIN_QUERY_PASSWORD: ENC[AES256_GCM,data:WhPlVv1pjOEMTB0hDyqAKU2GUFA=,iv:bqvX+UTmme861T1Fax8rTAkDh0ub/fQuRxpe+5JntQY=,tag:pt6oFiMW/vyhcHAhDtyw6g==,type:str]
    SECRET_AUTHELIA_SENDER_EMAIL: ENC[AES256_GCM,data:r8UGyF5/v161oywMNlRxXIPg7rdJO371zAML4DOi6sikzhZMEinCnTDZg7egN/RxauODlFtLl7/Yuok=,iv:zbshd8jNgR70MDHPt71fpJLiJBIq1HvvLu+WjNfNeNc=,tag:2uckw2TlCl/qkLBpfuMWiA==,type:str]
    SECRET_IMMICH_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:SOcLG6oNOUSXnamie0E60Y7w0LML/a3qVdTA4EoMwFTEa3bZSbn096STGf0TnhartofhoMkYGa/JPc2LmBxt9TG0nKsy1j+fYtSJodZNxDzwiDtiixrsPMMK46uAUf3V0w==,iv:/GwTlObnqQH/0VSxIK2PB0Pbw3Qs8wqnUeFqJyuTeVk=,tag:hZ984KGlrGie5+gRJCd3ow==,type:str]
    SECRET_CAMERA_PASSWORD: ENC[AES256_GCM,data:bYNMNpaS+FxSwZhD6X0zgl5H,iv:Bhp3acgtgnP1KuReI6UP871QOIiMBqqvBKqH+h5UnAw=,tag:z4BQPOM8ZRpC57LlmwTN7Q==,type:str]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:ncosNI0hCGRm117nQ+GFwxxpSBUKIvIqzXuL0CJAUuscx0sXsoxPq2jz7ynOuaOHhx1hF6G9W0sUbATOzbnzM7OAUPD+LoC5TXLUwc4FOX1Clq2eIj2M92nHfWk2J3u76IxCQIy7Tgy1h71VA6cVV7aOyh0r12uiDQ==,iv:ZIJlRt7CtICqnejJxPBcKeEIV2K98MZpx/fjwH66cEE=,tag:R+kzEjOWQvi97a9SW8nLVA==,type:str]
    SECRET_SHELFMARK_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:cC+/MxANPUeP+ls7Ip1RhCGFWZ4FHILFSpRpMPHagzVNcm8lA0LKA7LNUg2eaVIUfbbtRa/4HodsetCn,iv:m2Kt1jDjfgDtJzau6nH6NbWayUvBMMAX/AbLWg1KyvA=,tag:Mob/pxFW/nHtfLfbxMXRGg==,type:str]
    SECRET_KARAKEEP_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:nRvuNZ2KCXYoY44XvIExL9TPkXiO7BP8BZilcxUQ0yEPc5XkI3c+FvHRHuE=,iv:wJpxLmbJHZtuaV55ASy4H/xg/QFdULKdGlIQokAwzAU=,tag:rXeLt1ScUlzH95095buG/A==,type:str]
sops:
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTjFBQWh4SXFPeGwwNklM
            Y3N4OXlxM2ZFV0pyckVDb21DUU5jdWdKcGpBCjlDd0ZQK1dQZG1WZnJNZUdSNDl5
            OElmNC9HUjhZdEZoSUJZcVhTTGRiQk0KLS0tIEs4Q3FvcEVlYlRHMjFxb0JIeWFI
            d1k5WTZla0hGMFJpa253WXdVVVNSTUUKtsCalJBZZPv5Dd1/rFoH7NPvpoPOo7rC
            xr2tBrxca0bJu4gjktVAyIXBxvCpWvUiOZtBSSRzUsWqY2pWxKfhSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T18:45:31Z"
    mac: ENC[AES256_GCM,data:09cRt5Uh1hQRb8fWXlXBswQzHNGR9qlbnzuj9QiLXShc3/a/bbaXHyz9qQUegR22Kn3fHLLwTnb6zMtwJ6zsM9FzDdZcVJ4e4SJiyKiDWtpcwhet1RWfRoRHL0gdv0qfxq6ETCDj9D7eeEi2YE4Uf9OA+2AdIT9tY3jz/xgV+Nw=,iv:taLTNOQLwgN83gg0f7pSSL4/6bf5+SYmM1+pKtducSs=,tag:6NAyEk8E1RZs9tbbCP02Uw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
