apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_EMAIL: ENC[AES256_GCM,data:8Nx+lUNFe6UnemuzVEeTXpdz9wK9qRKQM3o=,iv:+7L6tMM5TPjvgYKeSweC42ocKqONzUMQI0O4C8Zh8M8=,tag:UVqzS6/WiJdDfzSI2TyEeQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:2i8bYJbMimm9v3o=,iv:uSMk33DWug7Me9QscI6KYPCkSxfMlepDovnlxMn5uhs=,tag:LhcwDsnOW0z4KQ+URrsAbw==,type:str]
    SECRET_DYNAMIC_DOMAIN: ENC[AES256_GCM,data:cwwWzq2z02AamGp/uxA=,iv:6155jgndHvWmw2HmdkSP62NdAm2e5FdjUgNoyu4AU08=,tag:F50axIdKopUeNcjd8goO/w==,type:str]
    SECRET_SMTP_HOST: ENC[AES256_GCM,data:/0riBa3CmJtyf5RmMKdW1g==,iv:xigpTmRE5dpQccmfLYtDzTWnzGE/5Wbu48wVCObAMNM=,tag:2bw53M5rkQVRWzlFEJI45A==,type:str]
    SECRET_SMTP_USERNAME: ENC[AES256_GCM,data:Z5uMNMjEVGAYCNxT5CwohOw=,iv:k/r2gZA+Xx1IE6wj/NC3KlPeSKF549/0a5UVs5wEmU4=,tag:eIwQo6giC0iskcM1GG+6/g==,type:str]
    SECRET_SMTP_PASSWORD: ENC[AES256_GCM,data:DnxpNHtq81FHq52jN2pjekTzpSk=,iv:6Xvwnxv2hC7H3P/nGY6F8tMgAoS9ZqieNUJLeCm4NYY=,tag:UpNnzCnszCb5M5eSKPwVxA==,type:str]
    SECRET_JOPLIN_NOREPLY_EMAIL: ENC[AES256_GCM,data:FlBihq32wdz382QiS445sansYv4kAVab,iv:weG7rjk0ivQsTDIqRhs6Dek4TtNKfNqPsngUof2ICsU=,tag:GuJTbjmSOMCiecTw1sgfEg==,type:str]
    SECRET_MEALIE_FROM_EMAIL: ENC[AES256_GCM,data:nr10bMBMSJPDOTu8RezP+j1hnmOafcv5,iv:xOUZYqVia2WWW3HSFlYQLBt/NaPVTLTGNSmPcT8qdWM=,tag:VkN+l2glqVPhwFMFo0GLVw==,type:str]
    SECRET_LDAP_ADMIN_BIND_DN: ENC[AES256_GCM,data:6cxh0Oy35REWl5bVthkt7xdnhtrYrfx2B3bYlQ==,iv:jCndIz1LxK1ZoB4qxPc/h+Gu5XW3oegjpg9ThNItfR4=,tag:W1Q0WIExZPLf9FeamHPW+w==,type:str]
    SECRET_LDAP_ADMIN_QUERY_PASSWORD: ENC[AES256_GCM,data:xLuAJKVzxvpcWf9SZlqKEQjqvCE=,iv:gzxWo5kp1lhfBgtXxvgW0wSQ/GV3vUB/058ZmlhyIao=,tag:4mkDic776pTRjleIqHjgBA==,type:str]
    SECRET_AUTHELIA_SENDER_EMAIL: ENC[AES256_GCM,data:E+1bhilkUyZmcOV69LtavUwCKGSb20Vzf5yYz+P1LPbRux9Xta0ocforYjBT9xIa14ddPvC+X9a32SI=,iv:meLwvv/SuX1X35ZoLBeeT80dSR1kX5LdI8zkwjrfYaw=,tag:oRb5v8SkrPlu2+5OCK89Hg==,type:str]
    SECRET_IMMICH_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:oq0TGIOUhP4JqQhXvJibepHM0SpjxOwT6bFakytgJExZL7JvPpR4deD6CcBwxdVZuWM1L6gGu6N65f4MqG/ZiMfUWjct1eRqCjsxboiOfugGl9x5eiXz1CTg4xjO4KojPg==,iv:1JfzWBvhktvMMhg0TbMtU+MOdGRwz2Hj3eyas0sbvOM=,tag:vIIkry67msanjsUykLG/xA==,type:str]
    SECRET_CAMERA_PASSWORD: ENC[AES256_GCM,data:vv23wk5vIA4mIVL7oB0NCbib,iv:CwIaSbJ0aW7b/2/zF3wEv/uHv0/wylk/8mpWyNVBTSE=,tag:+2nZNyJUCLMh/vb4UzSHvw==,type:str]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:nuhxJI8GYFNgG8KYMFl7OZvBebgayVjmBvqRPcG4p0Y4MCBOAOaEPy05W4yxrEv1pSFYNJVBvO/1NK9TMx8z+v7luyKXBOBA497K3vNsORGR08WEnCmWdRWbWyq+CVOVdsan6XfegrdyM9nhcczAKfZdka3+Tv/wTg==,iv:SlziqOzaJbJNV+LkP2X4bnFH4P6EIHiG9FUaOLccxfM=,tag:ClUpUZutlxHXMjIhHrBpsw==,type:str]
    SECRET_SHELFMARK_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:ZWF7s8WqxqaKRQ5L3VHIDCHhpLRR89LUkundre9i7KIuAThgmiHzykPdf+gz+5j8nqRg8MBzx4RgXx+h,iv:7+N7F37W4g+BIUHaYtofW0u2pCoJoQQKVcPvlZXDFe4=,tag:sb8pohLPzJKx7s0JvUzHuw==,type:str]
    SECRET_KARAKEEP_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:L3cWS8BgVBwCCFj/67L1jOQsGC1YGcPZ/6Fxjr01GnfWQWksa1ZFExzK9A4=,iv:ZbfvAttb7TV+A2MTpDlpil6Cb9876yHcXAg6ae0z7Dc=,tag:jTGcETSlTwl0tWHe3bjCvA==,type:str]
    SECRET_DAWARICH_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:VO0RnU4XRwXkG0bl5xyoBrD6VbAxiNUGv6nZHoc0gvzsxt3RuW4/hDUwa5nBKaDgLEKPp1KWx9ENEFiQSPEypg==,iv:Hw19R4suO4+OXeD6zI3MMDxIPyMilP7W6ebJhTJTxgA=,tag:eEh4tgdmLE7TdWdeKhT7uQ==,type:str]
    SECRET_YAMTRACK_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:ol5hNQrbFhvCInrXI5Dv+XOatyuuFiYLXfLRiHVBeD2uhvKoZiMiuDtikCKj9/9dPLRQ4qPEjDPlrvnWVVLyGA==,iv:PWxL4/RJ9+V/4BDGB3Qki/v7G1O47UZ06k7s7sfK1wI=,tag:kwOUv75vOMCPxatAf7ijWA==,type:str]
sops:
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6b0RrN3RGSmdqekR4MkR2
            dEhFM1VOOEJhNVBLWldOUHJncG1PR3YzL0FJCks4TVpINWdjWnpONFl3NkZ4eUgy
            U1VYMEJrTjlzM1JmTHhxTEs1bnBaMzAKLS0tIHV6emJ5Mzloc3ZWVFdUenRkaHAw
            UzdGSlVYWE4vaG5hQzMzVnpvWFc0NlkKkFiavstXSmAbLC6Q4RUgVG1eXzy50OzS
            OCvqpynHIWQ8GPbe9MPDlRHgckvyjp2zlDXehAE7V42r71WDwxsUkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-12T08:52:25Z"
    mac: ENC[AES256_GCM,data:W3qxpiWvjMAtp3dEQRDjbAG8cA0nOmNr5c84kPir79thPOgfz2OqG3JdZyqEUBMsoMKyLczDKlM1C4lJuJU4dcIyjLF0K58/vAnG199UO0RKc33Hu5S8Wrhpnve0a8yAGeaLSW4OzsF4VVKU9NgFXl9A1E8jN4cGm095jGAo3wo=,iv:wD2cTK8U8xzLKCf/ceUMeNDO/lIPMiOj+LI1P8IBL3I=,tag:9025+tmpfoBeQGY7fEzPng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
