---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-pvc
  namespace: media-automation
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media-automation
  labels:
    app.kubernetes.io/instance: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: radarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: radarr
    spec:
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:6.1.1.10360-ls300
          ports:
            - containerPort: 7878
              name: http
          env:
            - name: PUID
              value: "1026"
            - name: PGID
              value: "100"
            - name: TZ
              value: {{TZ}}
          readinessProbe:
            httpGet:
              path: /ping
              port: 7878
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /ping
              port: 7878
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 5
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /media
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: radarr-config-pvc
        - name: media
          nfs:
            server: {{NAS_ADDRESS}}
            path: /volume1/video
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: media-automation
spec:
  ports:
    - port: 7878
      name: http
  selector:
    app.kubernetes.io/instance: radarr
