apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-uptime-kuma
    namespace: home-automation
stringData:
    MQTT_USERNAME: ENC[AES256_GCM,data:KeZDQRSUQhukSVk=,iv:Yt/szUxxZ3ywDGUKHs08RMghDlfQO/n/hkMdw94Pd34=,tag:QuCX30HZNWC2iG9zKdTbmw==,type:str]
    MQTT_PASSWORD: ENC[AES256_GCM,data:2WqDDpQsTirCDO5o0LAoBuOE2XAySL+fiQ7uzlEKWdY=,iv:SpBFAhOPPnE7IWHVJBLBZ0Y1c+jYeRVfiwKYD2cIR/U=,tag:owRGD4T2FW6RKhjP9pglKw==,type:str]
sops:
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1OU5PTkxzVkV0UTNYRjNz
            TUh2SWtGU2h0cHB2Q3ZFVlYzdFp5YmhicXk4CkhtV0FGWWd5ZlVvZkdhaEpVMDh3
            TDhCTkU3aE1XQ2hESlRqMFVYWXJmb2MKLS0tIEpLYUtUUktFUWFJYVhOL244MGg4
            Ni80RkFyUnd1bk5DWXJzOVhhclpNUVEKB81LhGd4fI63CaO7rcQ9BNpKUQ3Vwjlv
            ACTyi+HsXEP+YQpPWq9XpckmC1RHWSISyDxzBPYkK6BX4Ybsbk7bMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T15:11:42Z"
    mac: ENC[AES256_GCM,data:Hq7MEpjNnwCXTSegCwW9YDnHkIpAS1u1tBdrnZ2nnu0WiM/P1d7jdTwXOtYSPsZnwLni3eKrCCtiqlkWOhLfsgEJO/jp7DCy4nkWmGTW8ceViVnyAQ1FXuLYyLqD0HR3LGvGVgiWPjZ1c8KUA90ubJTVjsRLqVy4qjWLahnq5gI=,iv:CUdX7xi8li+ByrtaTMDOilIUx1yY++coWTZyLgV9GMo=,tag:IQ3CT/NXAGN+A/TPXmznpw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
