---
apiVersion: v1
kind: ConfigMap
metadata:
  name: yamtrack
  namespace: yamtrack
  annotations:
    reloader.stakater.com/match: "true"
data:
  TZ: "{{TZ}}"
  REDIS_URL: "redis://yamtrack-redis:6379"
  URLS: "https://yamtrack.{{SECRET_DOMAIN}}"
  REGISTRATION: "True"
  ADMIN_ENABLED: "True"
  SOCIAL_PROVIDERS: "allauth.socialaccount.providers.openid_connect"
  SOCIALACCOUNT_ONLY: "True"
  REDIRECT_LOGIN_TO_SSO: "False"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: yamtrack
  name: yamtrack
  namespace: yamtrack
spec:
  selector:
    app.kubernetes.io/instance: yamtrack
  ports:
    - name: http
      port: 8000
      targetPort: http
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: yamtrack
  name: yamtrack-data-pvc
  namespace: yamtrack
spec:
  storageClassName: longhorn
  volumeName: yamtrack-data-pv
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: yamtrack-data-pv
spec:
  storageClassName: longhorn
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '2'
      staleReplicaTimeout: '2880'
    volumeHandle: yamtrack-data-pv  # we have to create it manually on longhorn UI first
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yamtrack
  namespace: yamtrack
  labels:
    app.kubernetes.io/instance: yamtrack
  annotations:
    reloader.stakater.com/search: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: yamtrack
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: yamtrack
    spec:
      restartPolicy: Always
      containers:
        - name: yamtrack
          image: ghcr.io/fuzzygrim/yamtrack:0.26.3
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: yamtrack
                optional: false
            - secretRef:
                name: yamtrack
                optional: false
          ports:
            - containerPort: 8000
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 5
          volumeMounts:
            - name: yamtrack-data
              mountPath: /yamtrack/db
      volumes:
        - name: yamtrack-data
          persistentVolumeClaim:
            claimName: yamtrack-data-pvc
