apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: yamtrack
    namespace: yamtrack
    annotations:
        reloader.stakater.com/match: "true"
stringData:
    SECRET: ENC[AES256_GCM,data:svJJXmLAvOWBpVRliCd+w3Xd0akNOCJIOZGuFxGNbkXP1uaz12+WJUM7yQXT24NGGwel+STMpG5yHSUPhhg5mq5AWANwk8Owk+fEi0D3H55OptNW4X+4xw==,iv:bbcSB9vYQm6gdvYnwBEqZXUpCf62fKu+ztEOU7ZEC+4=,tag:LndBYMGHMnDfV+z1fnExoQ==,type:str]
    SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:D+hnRpXk9pM4REM9RWSWVSCaUU24eBjtRpV9vk7yPFZ7SNxNuMlcl8orOwIMBUlN3ELU2EQDIxMM7q9IqdBavPJpNY/hCnjSViWJffHXa5vCQX23OZLL3rRH5I4CXJxpxIhGZeL8clThUUsTRryHH1C7nx4gEWSqZjtNEAv6d6E151z0mE1+eMcaHWvmQOBwZY1o2JuTamydy1c36spDjElw4SYG8WyqHOWXfrNe4GpFVGKymYRqroPfokgD7P8GBA0GPQ4zORSHq50UgPEytsmPLzemNl6xhOFHQLcrnzf8mrjVSx1gVwysfvqgjAhiMpgQLEcyndx3JrqqPhDxmi/YRHffOqe1AeHm+R/gm8SB+P/XTOxlhwMmMJ7P,iv:5pfbQKIrCBNWYmLG/hOHluW6MsEnmiGSeBExtX6eaog=,tag:9H8jC0HO4is0fK+izNb0JQ==,type:str]
sops:
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UytzRjZzeitYWkhqTUhz
            MmYvUk80UnVFRzduY00xUFlBdEtsZXVNWlVvCnlKODFXOStwcmFabGJjV0k4Mmls
            SGdPQzhTSEZ6OGVsT3lZdXJNSXRUTFkKLS0tIFljSjF2MWZiNktQQXlZTGpac05X
            QkJIL2xxVzNQUkZlUS82MWloWk91UDQKqRRnLqY1cFx2tvNNWoILJP4Vd6wPZ8iO
            xhGSg3dqqpoAPU+H4hYtDJt3eXAWsBhC/+303DeZJJpDoM4Ff5VJDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-12T09:16:54Z"
    mac: ENC[AES256_GCM,data:dPQqe220QcLAXrgE+sgbOHBuX9uosbrqNENLdV4ekgMBe91EOM3FKsIT9xOAld4p/sPWXXOHtH79ovJbnJ5EamBmL/PW2UERsbu7QSHmX/n0lJaAOOnUnqIs6aAx0pEGEL3fWRbniJTA6xo+isgr4WXJq6rBKFBZ0MviQX+J9Fk=,iv:oyVihf00FgLvqWFUlrtZS/aOY+AvlyB3Xd1RFoCpCp0=,tag:H5Y7BUQd409NIY/ehNpX9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
