---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-pvc
  namespace: home-automation
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  namespace: home-automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: open-webui
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: open-webui
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: open-webui
          image: ghcr.io/open-webui/open-webui:v0.9.5
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 18
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 30
            failureThreshold: 5
          env:
            - name: OLLAMA_BASE_URL
              value: "http://ollama.home-automation.svc.cluster.local:11434"
            - name: ENABLE_LDAP
              value: "true"
            - name: LDAP_SERVER_LABEL
              value: "jlejeune.home"
            - name: LDAP_SERVER_HOST
              value: "openldap.openldap.svc.cluster.local"
            - name: LDAP_SERVER_PORT
              value: "389"
            - name: LDAP_ATTRIBUTE_FOR_USERNAME
              value: "uid"
            - name: LDAP_APP_DN
              value: "{{SECRET_LDAP_ADMIN_BIND_DN}}"
            - name: LDAP_APP_PASSWORD
              value: "{{SECRET_LDAP_ADMIN_QUERY_PASSWORD}}"
            - name: LDAP_SEARCH_BASE
              value: "ou=people,dc=jlejeune,dc=home"
            - name: LDAP_SEARCH_FILTER
              value: "(ou=internal)"
            - name: LDAP_USE_TLS
              value: "false"
            - name: DEFAULT_USER_ROLE
              value: "user"
          tty: true
          volumeMounts:
            - name: open-webui-data
              mountPath: /app/backend/data
      volumes:
        - name: open-webui-data
          persistentVolumeClaim:
            claimName: open-webui-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: open-webui
  namespace: home-automation
spec:
  selector:
    app.kubernetes.io/instance: open-webui
  ports:
    - port: 8080
      name: open-webui
      targetPort: 8080
      protocol: TCP
