apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: floppy
    namespace: floppy
    annotations:
        reloader.stakater.com/match: "true"
stringData:
    SECRET: ENC[AES256_GCM,data:DEXesS7JHwSgCSoHHGtab1mw/Fa8tRSj4yav4P0lyD75V5a3Vqqlx916+i98w4t8w0XC+Z4ldEwP2SsXK2PlQ08PYllkqHS/bjUcVEMy+04qhLO2dxWe8Q==,iv:fShPh6j4DqG/RFwgz3JhdvwKR/gj89h0vo5Ny74CRQc=,tag:yVj9X1oB1m7FQCPEttJk0g==,type:str]
    SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:miKzwwXu6w2QOB/+QcUMhRQwjN5CEFo/CQTPbI4biDx8Gqjz1tl04ZcB3jV094hnoc78F1IlP+1EKf16wphLvrjdxIXu9vpHG/WeSc39oTvTexc3RkI27isP+h5QISd8f+nBrL3fgoyv0Ajl5f5cEl784bHXUz2fs8+TEdEhy34zuhsIQczmzB8oksYhhI5Ck47RMAVwb+zboFx7eq4H+UrVKMiESefxnbw3jAqGgHogLckyqxHQsJ/Ny2IwfNpLX7v7+1yQINGOVc0fVjEB/DUX+Es/2WIcmj3Qbh7Wq9omNdiU4fohTrbej0XFPggWIVIZl+Z6GlKUKO8P5uoOqds69U43aLArYksW8Wg/iPyaBRwYCMJ1J9BVFg==,iv:s4K/ywXWhmsii0gl4dPF1jMnPwbjLDJJZPmdmOHaFRQ=,tag:MqZlOlixKZ7GjSu9xoPypQ==,type:str]
sops:
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDL0JPQ2dVNEZobmsvWVVL
            cjFJZjlvTmJ0RmM1SVFKcVlTZ3J1SkQ4eGhZCmFnemJBbW15Yk1jV1pIcHY5L3BZ
            a3dXdS9vZFhvTHBIbnNPdWZrTHZ5dnMKLS0tIHRTbW9XYnpBakpqenBJb1kvSGpa
            NldwL0FQYzAxbVFEVmdUMVRINTAvc00KR3io3tp2AjquZJvmVhanvv05sIXksj0z
            Z7VWMAnKZglInHbOeGeS003Otz0RKg6ba7GttKJCH5jsqV31mLsqyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-23T14:49:12Z"
    mac: ENC[AES256_GCM,data:lVrtbyjfwnevA3JlshTU3USMq5f9+TJ3pXmRefRUdwgFsEj0hOaMC0IMw+GCkN4NFLUu9GUu+OzdBsYfUAt3lAcgY51DNG7aflkgnxwI4fotd2lDU2fQMCzbpNKUNkmlgv53By94IkkZ9Zl1wt5AR/AZZt0P6+Ke2d5CgblHGnw=,iv:73ajpRaZXClcaPOVdTQqExTn6YKZrJjIdfzZb6AAEbk=,tag:g349SIRqyjZltKWaEaBMLg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
