---
apiVersion: v1
kind: ConfigMap
metadata:
  name: floppy
  namespace: floppy
  annotations:
    reloader.stakater.com/match: "true"
data:
  TZ: "{{TZ}}"
  REDIS_URL: "redis://floppy-redis:6379"
  URLS: "https://floppy.{{SECRET_DOMAIN}}"
  ALLOWED_HOSTS: "*"
  REGISTRATION: "True"
  DEMO_ACCOUNT_ENABLED: "False"
  ADMIN_ENABLED: "True"
  SOCIAL_PROVIDERS: "allauth.socialaccount.providers.openid_connect"
  SOCIALACCOUNT_ONLY: "True"
  REDIRECT_LOGIN_TO_SSO: "False"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: floppy
  name: floppy
  namespace: floppy
spec:
  selector:
    app.kubernetes.io/instance: floppy
  ports:
    - name: http
      port: 8000
      targetPort: http
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: floppy
  name: floppy-data-pvc
  namespace: floppy
spec:
  storageClassName: longhorn
  volumeName: floppy-data-pv
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: floppy-data-pv
spec:
  storageClassName: longhorn
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '2'
      staleReplicaTimeout: '2880'
    volumeHandle: floppy-data-pv  # we have to create it manually on longhorn UI first
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: floppy
  namespace: floppy
  labels:
    app.kubernetes.io/instance: floppy
  annotations:
    reloader.stakater.com/search: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: floppy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: floppy
    spec:
      restartPolicy: Always
      enableServiceLinks: false
      containers:
        - name: floppy
          image: ghcr.io/dannyvfilms/floppy:26.8.27
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: floppy
                optional: false
            - secretRef:
                name: floppy
                optional: false
          ports:
            - containerPort: 8000
              name: http
          startupProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
            failureThreshold: 90
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 30
            failureThreshold: 5
          volumeMounts:
            - name: floppy-data
              mountPath: /floppy/db
      volumes:
        - name: floppy-data
          persistentVolumeClaim:
            claimName: floppy-data-pvc
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 80
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
