---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lldap
  namespace: lldap
  labels:
    app.kubernetes.io/instance: lldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: lldap
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: lldap
    spec:
      containers:
        - name: lldap
          image: lldap/lldap:2026-03-04
          imagePullPolicy: IfNotPresent
          env:
            - name: LLDAP_LDAP_BASE_DN
              value: dc=jlejeune,dc=home
            - name: LLDAP_HTTP_URL
              value: "https://lldap.{{SECRET_DOMAIN}}"
            - name: LLDAP_VERBOSE
              value: "false"
          envFrom:
            - secretRef:
                name: lldap
          ports:
            - name: ldap
              containerPort: 3890
            - name: http
              containerPort: 17170
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            limits:
              memory: 100Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: lldap-data
---
apiVersion: v1
kind: Service
metadata:
  name: lldap
  namespace: lldap
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: lldap
  ports:
    - name: ldap
      port: 3890
      targetPort: 3890
    - name: http
      port: 17170
      targetPort: 17170
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lldap-tls
  namespace: lldap
spec:
  dnsNames:
    - lldap.{{SECRET_DOMAIN}}
  issuerRef:
    kind: ClusterIssuer
    name: jlejeune.home
  secretName: lldap-tls
