apiVersion: v1
kind: Secret
metadata:
    name: lldap
    namespace: lldap
stringData:
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:6ynEOWA+GlNyv3Wz+ck9nYtDjrn/cVuFLS2jF2EElmtF0j4E0FatNF2EcoZk5YY90+l8XpeD5wGwa7CDEdxlmQ==,iv:sdYuXJTJMEFWoxDfs2yhdZOaCuWlRbEXPoOoNEdg52w=,tag:TgGHMCgHeeb7HUSTEx6HFg==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:hlPKWRueizDOqkKCUWEBh2zgbjM=,iv:PZbCbebei41m6S5MTgaM+pGUOAZtwrguVvh5X0FzC8g=,tag:D9lVY0q1gSh7lfiuDyI1hg==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieTg3M2JwOVZ3bnVxNk1l
            VnNBcTlNRXQxdEMvbjRaZVU1NEtKUHlpUFdVCkNURkxSN3N5WmpGOWhXS2pYcWpQ
            T0ZTT1pjc2JXa1hBRW1VUGVpWjVFR0EKLS0tIEJ4bzNlSEdVT09EeCtYZjg1b2cw
            cFJ1NnNOSzBFbVU1QyttWk5ORFNsVFUKr/10zZUgD0I8CjyrLnZGWrfUEFeQ9ISA
            SAID5Mz0uCszh+2d6ERVPLuYESj/+r9BY8q1RqsXbCfebXRxJLOAuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T16:38:45Z"
    mac: ENC[AES256_GCM,data:9t7NItMDZaUH369oWIpBd1TKtkimU9O/wOIZyEaZxWp/QHSgdph/mnJqLE9Ij/wRGgXpGkJxNfZbcd2IZsFCBf5aJzi3mrBs8uJb4Hi6fz9FMo18VjlfHasZ2TaDDAcmPLDlknCjTDyRRrr6WjRA0bS39BVFKlnws7pWykAWSZk=,iv:UStPG6WTHmC7mx3nB2nSj/zDCDpklVxwYqkTNxZ3hAM=,tag:cyY9ZHt+wDt6MC24Q24kWg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
