---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-config-pvc
  namespace: media-automation
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-metadata-pvc
  namespace: media-automation
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
  namespace: media-automation
  labels:
    app.kubernetes.io/instance: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: audiobookshelf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: audiobookshelf
    spec:
      securityContext:
        runAsUser: 1026
        runAsGroup: 100
        fsGroup: 100
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:2.37.1
          ports:
            - containerPort: 13378
              name: http
          env:
            - name: PORT
              value: "13378"
            - name: CONFIG_PATH
              value: /config
            - name: METADATA_PATH
              value: /metadata
            - name: TZ
              value: {{TZ}}
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 13378
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 13378
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 5
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - name: config
              mountPath: /config
            - name: metadata
              mountPath: /metadata
            - name: podcasts
              mountPath: /podcasts
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: audiobookshelf-config-pvc
        - name: metadata
          persistentVolumeClaim:
            claimName: audiobookshelf-metadata-pvc
        - name: podcasts
          nfs:
            server: {{NAS_ADDRESS}}
            path: /volume1/podcast
---
apiVersion: v1
kind: Service
metadata:
  name: audiobookshelf
  namespace: media-automation
spec:
  ports:
    - port: 13378
      name: http
  selector:
    app.kubernetes.io/instance: audiobookshelf
