---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-rendered.yaml
patches:
  - path: frr-k8s-patch.yaml
    target:
      kind: DaemonSet
      name: ".*frr-k8s.*"
