---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - openldap-pvc.yaml
  - openldap-bootstrap.yaml
  - openldap.yaml
  - lam-config.yaml
  - lam.yaml
  - secret.sops.yaml
