---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openldap-data
  namespace: openldap
  labels:
    app.kubernetes.io/instance: openldap
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openldap-config
  namespace: openldap
  labels:
    app.kubernetes.io/instance: openldap
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
