apiVersion: v1
kind: Secret
metadata:
    name: openldap
    namespace: openldap
stringData:
    LDAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:SVdg1NLcVgaXb3N/F1EoF5u8XUk=,iv:ojVOMRDh/qVTIfltQH7MU7y1j2PFyjHzLnGFQ9fYYcY=,tag:/HMSuRKKZN1/Xt/BLn0xRw==,type:str]
    LDAP_CONFIG_PASSWORD: ENC[AES256_GCM,data:ZEGxll94RgJ1S3inW+YTQIejSslO9TGYd+FDIhifo40=,iv:LYs9G58ukZEz5sK+gRQ/kdjOl2/Cc+9PUuVasfAcSQ0=,tag:kjjfcJKGoBbRpfhAkVDvdA==,type:str]
    LAM_PASSWORD: ENC[AES256_GCM,data:xij4j1KhMojjMy/KGVx7odRqZFRZvNCuA3iqmWcgtM0=,iv:HbjJxSafK3i/q43E9jiyiQyqys0wVZT/KZqgirY2mnA=,tag:vsEGdWAHZe/3KubBXEf/HQ==,type:str]
sops:
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZGt3L1BFVDBQMXZOeGZT
            cmFyaEFHMUFHRWFPYjZKbys0T1dpQ0NjV3lFCmZEUzV4TlBJenNjS2VQcnVoM2Uy
            OVZHL2plMHNwNCtxVjRnVDlnVE5qMWsKLS0tIGtBMlUvbkNBY2JMRHVMNUJXMEFx
            MEdibFgrdkhZM0U4WlowdWdPa1d2alEKw9XiXvEIwLEIcxFiZH37CKqF7770K3K4
            Qf8os/ucp9NI9rKbZss0lRhz6xJh+Y/J7ZWBP6T99rEU0vqqFlUiwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T15:56:59Z"
    mac: ENC[AES256_GCM,data:8tRSEtd4OBfTLozsudAgFAfxBJLYB5ctYgL7sGUwRDmgM9SifyFA0Yym09etmP48NJ+rIHvmXt+9ZhRfjnleCpPZYyPZDgl55iEUdHe1NmYgJwts4GuVvIPldGTvxuv9ar/q7p7Ztd56mrT9gcELqv+/ig6Dqa82kATJnQn+TEg=,iv:FoifPMIZLqj1TZ7yFJSfLY6bOrO3rerwcJlVd79fCfQ=,tag:40bfb02vYLnnCwq30Bk7Ag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
