---
vars:
  - targetPath: SECRET_DYNAMIC_DOMAIN
    clusterSecret:
      name: cluster-secrets
      namespace: default
      key: SECRET_DYNAMIC_DOMAIN
  - targetPath: LB_TRAEFIK_ADDRESS
    clusterConfigMap:
      name: cluster-settings
      namespace: default
      key: LB_TRAEFIK_ADDRESS

deployments:
  - path: .
