---
vars:
  - targetPath: TZ
    clusterConfigMap:
      name: cluster-settings
      namespace: default
      key: TZ
  - targetPath: LB_SMTP_RELAY_ADDRESS
    clusterConfigMap:
      name: cluster-settings
      namespace: default
      key: LB_SMTP_RELAY_ADDRESS
  - targetPath: LB_OPENLDAP_ADDRESS
    clusterConfigMap:
      name: cluster-settings
      namespace: default
      key: LB_OPENLDAP_ADDRESS
  - targetPath: NAS_ADDRESS
    clusterConfigMap:
      name: cluster-settings
      namespace: default
      key: NAS_ADDRESS
  - targetPath: SECRET_DOMAIN
    clusterSecret:
      name: cluster-secrets
      namespace: default
      key: SECRET_DOMAIN
  - targetPath: SECRET_DYNAMIC_DOMAIN
    clusterSecret:
      name: cluster-secrets
      namespace: default
      key: SECRET_DYNAMIC_DOMAIN
  - targetPath: SECRET_LDAP_ADMIN_BIND_DN
    clusterSecret:
      name: cluster-secrets
      namespace: default
      key: SECRET_LDAP_ADMIN_BIND_DN
  - targetPath: SECRET_LDAP_ADMIN_QUERY_PASSWORD
    clusterSecret:
      name: cluster-secrets
      namespace: default
      key: SECRET_LDAP_ADMIN_QUERY_PASSWORD

deployments:
  - path: smtp-relay
  - include: mealie
  - path: dashy
  - path: donetick
  - include: authelia
  - include: networking
  - path: freshrss
  - include: joplin
  - path: jellyfin
  - path: immich
  - path: yamtrack
  - path: floppy
  - path: openldap
  - path: plik
  - path: rustdesk
  - path: stirling-pdf
  - path: thelounge
  - path: karakeep
  - path: dawarich
  - path: supabase
  - include: home-automation
  - include: nextcloud
  - include: media-automation
