apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: zerobyte
    namespace: zerobyte
stringData:
    APP_SECRET: ENC[AES256_GCM,data:CYXx6hp4b842ZSPKsnZbwAbB8RzB4BUSM2mA0EDII8Vz0hyWQb1vWOA7fwjPNjxkQD7H1ZuTIX3c5JS5CAixtw==,iv:2DEonpLv/MYfavx0o2QOyGGVzO8/z46lO3k50O+gBh8=,tag:W/XEKTfkvS7DZ8UHwE9nGw==,type:str]
sops:
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMWxPc3dvUzVVSWNZaS9Y
            Wk1iSmZ0eHVPYmJNWUdxVHkwVzdjai82cldrCjJoNVA4YVFKWlNsd0NmQUhNcjY2
            dXJSL0dNK3Bjc0loTHFTRzJtV25maFkKLS0tIDk1ZEpiM2xKQjhEMi9CS0tTYkV2
            NmM0aFE0R0FlVi82NCtyV0pINElsVHMKVtJR7NGQ/AsZWroS2AWY5rXcpeE1DpR5
            daC9VswY2J960N7ODdHnvcJONtpHK567+nO8C8h9hkFXENxwfheA6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-05T17:47:27Z"
    mac: ENC[AES256_GCM,data:28NWuq9ThNk6+QgZOJAoqmHCGG5f7mZHB0P43feJzYzbVWo8+eMhW1pbCLI8Q8pBUW86Nb6HW0gx/GVAFjKuLkekVUkJqUtZp11FBDvSOHk9f/u9dp9bxCrCe1qxnlg6zJ+yWdHK9r+TgCxzEEv++hsY0rUgVwhwq2QaBjWQHiI=,iv:Pgk+zluQgeOwA9XZkxB9W+1yg4gETSpFsxv7AvZaPVQ=,tag:suliCpjaDTnZch1WBsm+ew==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
