apiVersion: v1
kind: Secret
metadata:
    name: hermes-agent-secret
    namespace: home-automation
stringData:
    .env: ENC[AES256_GCM,data:1wphwwNJ7j8JLsPcm6ajDNWgYVWeVDDf1UT3Tlj+KWXTB0LoTeYAwD1/FVUCOTzuCTn7ATYfipWv0YPjIEPdbE2/3swyW4dtC0CfHZwC1RDkJCMjtuhjFFXGItpjhmLtqfqABCdSV2sh1ELPce3dcR3bmo06KI35OBS6dJhtlnekAV2k,iv:in+DVKh68NCTwP8NlKMzoavtQbP6VywLwH6HTV3F6aI=,tag:dwDpj/4a/gG9Y+3O1ZakoA==,type:str]
sops:
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5K29zUnUrcHYxTmt4RjVC
            b3FNb29FYlhqc0ZxQ3R2ZUFhVVhKNHRHdUZ3Cjl3a0lOVmcxS2hpZ2s5NWZReEZp
            SWszMlUvT25YeGFJd2VxZlRXOVBNNGsKLS0tIEZ4WHJYTmw0Z0FWdzJ3VGFvMTdU
            M2V4NjVXNXNDNzlOb0FXczZVR0JyZU0KjF/O3O6HdpbDvMNCgcaHtYaXkAdraiJF
            nVYTnvgBMVsG9YK6lsZZzF5PPm2CAEOXmeFsapGGJa8Q1ozuYWC0xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T21:11:47Z"
    mac: ENC[AES256_GCM,data:logtuExWZIi5bcar5nfVNmpYAdXwkY6eg5P2k8Qi2RLhayr0rL4xHsuKoEK2uBEcAsL5+9530sJChdlVS8IiewMbuuA9cltkgbRNX178++j9aBmL8PEyXohZv/XJ0gyZ30TP+urwFtpvdbJaQdmFSl9r4shcuvE4E6fA4teod2k=,iv:ACHGPcsHFDsNuCz+n0JB3zOuJ+j+QpDdwe7qzBXWQc4=,tag:foAYE74cmdEOz9/TYjXWxQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
