apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-prometheus
    namespace: monitoring
stringData:
    TOKEN: ENC[AES256_GCM,data:Rxh7euFocEV0iZKn/m83htchOyGFLwBtyObivLJtYVBVuDqZWUKWEGH8TevunjqKWgmtpZYAZEIGUSiLKMQU/3f3b7uvKIvBWFvvBi6nwWJb19u0DKBJE3ySLcAyiemiZ7Dd93rgQc9W4kzLt5LVwfABDghRBW6dJWAHreeV2bX04Zdxz7Gj4MwfUJqIP0Dq+T9FLUaJEL5XX5dDnm0PGSIXD/KuiqjLNDLs5XACAoVUPVnOVzKJ,iv:7kAjdHN1gpXUQMW9HlHW8e8/5UbNd3KqYKtcdWRupH4=,tag:R2jolhCB9kHbPn6zHMljRg==,type:str]
sops:
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2R0tURXFtMmZHMjlEMTRC
            dHlDK0pVaWtEdkVYRFVtV3BwbHo2N2p5b3hjCkFjT2llYlFGUi9PUm1xS0pieFND
            N2grZklDSHA0Y0M5M1E4UExnWlhtQkEKLS0tIG1nSzFzMmNpdGErb21MY1BtaDlT
            ZGY1L3ROMmlTZVRJQXRheVlHYlBYdFUKo7lY+BbpTR/mEElLvUfdtYs3kWyA4ETR
            wwqgeU45gPYVz8ADSUgnOorndWuKVgMG/6+T9q+6Chq7RkFuZ1EQzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-28T18:10:35Z"
    mac: ENC[AES256_GCM,data:HuQw2ww10WGqaXJPC1gyChhDfGpw9V8aHGxEvXk1Wj2sSj6bJmNLjz/LLroJG646oHxs/lWnJKIO0/173h8KivoiOvBcwRBV/aZP18axU6dGTImPM9t0W0NV7B5qWInCUVYvGVyShIwnsMK0Sf4gOY7YDQqZSJAjVmRTBUV3kWw=,iv:M2FTe99cWZNYw1VoRhqT88E3YgjKjSoteVDZEfeYZG0=,tag:1a8II3D6TGLs7GvmYtos8w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
