apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: karakeep
    namespace: karakeep
stringData:
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:6WgwbIjSFmcyoCFV9uVK3eJgDBIOoJ8lPNj0+IHQS3Aq1QXDHBPT9QZn3g0=,iv:8mWpNmW/rImlud68N8zlaY5J3OxkDYzlE5yq6bN7esE=,tag:xQlu8fZF9cefoW6kaQGpSg==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:1VCkC8ot5xU/nU2i97a+4z6MXpavb0I0jOBYEgIQoBD/QyidTXqwdVPAcOc=,iv:qi9PNRPdHe1Eh3UNNvS+TyoYnPccOokBI9mK5S7WnbQ=,tag:tVneiuXM0q4/xbJTMU3HhQ==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:v+sJnlN0rrhkNOpuTPFuM1U3Xbw0VbPNWh/EbVwcl9wLZPbv2muWv6xilk1BdHVFfdni6BOwT3MAumaRmwnzUg==,iv:pl8Qf3st/WFwSa5/4hvFDDKdBvjH5A9kgmFZdQD7uAU=,tag:EAPhaE15NhHI7nre4BCHNw==,type:str]
sops:
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVmVUQWkwRi81ZkhnZ1pC
            RlBvNlA1TVRKaWRDcHBaMm9vVXJNbklDblJNCjhKaXN0TkowblMxYWx3SEpwcHRw
            Yndtckp6S2hqclQ3WkwvdkljT3lFOFkKLS0tIGcvVXpUVGpnOHNTTDlKT0g1V0dV
            SGtOMkVid2VXcTkvbEdwVkdZUEFycVEKd3Ox/BQHkH2eRtS3lrD1VbjaukA7RO1V
            spiM4dKnsMzbCTXheYGyyck+qz3aPZhMKrrKO9nI6vAFN95EYhHHWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T19:45:50Z"
    mac: ENC[AES256_GCM,data:cA2wnyZIGPa0wCxF8K8hZYhwwjfnHgNzHKbTwQhtruTnaGuG5steIcQYUcIJlS8EGuNFRShnlMymCpx/QT4DsiaWEVXTqUo07l5BBneJlKYki8bdlLx70z0VRZAHeyroyBUjBfS8+sk6hl5JIcQWQ8r7SXTtb+YrI1aOA2Dpt1g=,iv:zgpc+mlDux1ECdRSNG3av53Ha/OB2dWC+6/KBqesmaU=,tag:DwPLoovS3nWN97zVVaZzCg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
