---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-pvc
  namespace: monitoring
spec:
  storageClassName: longhorn
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  namespace: monitoring
  labels:
    app.kubernetes.io/instance: uptime-kuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: uptime-kuma
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: uptime-kuma
    spec:
      restartPolicy: Always
      containers:
        - name: uptime-kuma
          image: louislam/uptime-kuma:2.2.0
          imagePullPolicy: IfNotPresent
          env:
            - name: UPTIME_KUMA_PORT
              value: "3001"
          ports:
            - containerPort: 3001
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
          volumeMounts:
            - mountPath: /app/data
              name: uptime-kuma-vol
      volumes:
        - name: uptime-kuma-vol
          persistentVolumeClaim:
            claimName: uptime-kuma-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
  namespace: monitoring
spec:
  ports:
    - name: http
      port: 3001
      targetPort: http
  selector:
    app.kubernetes.io/instance: uptime-kuma
