---
vars:
  - targetPath: LB_DNS_ADDRESS
    clusterConfigMap:
      name: cluster-settings
      namespace: default
      key: LB_DNS_ADDRESS
  - targetPath: LB_TRAEFIK_ADDRESS
    clusterConfigMap:
      name: cluster-settings
      namespace: default
      key: LB_TRAEFIK_ADDRESS
  - targetPath: SECRET_DOMAIN
    clusterSecret:
      name: cluster-secrets
      namespace: default
      key: SECRET_DOMAIN

deployments:
  - path: .
