---
apiVersion: v1
kind: ConfigMap
metadata:
  name: technitium
  namespace: networking
  annotations:
    reloader.stakater.com/match: "true"
data:
  TZ: "{{TZ}}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: technitium-pvc
  namespace: networking
spec:
  storageClassName: longhorn
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: technitium
  namespace: networking
  labels:
    app.kubernetes.io/instance: technitium
  annotations:
    reloader.stakater.com/search: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: technitium
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: technitium
    spec:
      restartPolicy: Always
      containers:
        - name: technitium
          image: technitium/dns-server:15.2.0
          envFrom:
            - configMapRef:
                name: technitium
          ports:
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: http
              containerPort: 5380
              protocol: TCP
            - name: dhcp
              containerPort: 67
              protocol: UDP
          readinessProbe:
            httpGet:
              path: /
              port: 5380
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 5380
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 5
          volumeMounts:
            - mountPath: /etc/dns
              name: technitium-data
      volumes:
        - name: technitium-data
          persistentVolumeClaim:
            claimName: technitium-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: technitium-dns-tcp
  namespace: networking
  annotations:
    metallb.io/allow-shared-ip: technitium
    metallb.io/loadBalancerIPs: "{{LB_DNS_ADDRESS}}"
spec:
  selector:
    app.kubernetes.io/instance: technitium
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: technitium-dns-udp
  namespace: networking
  annotations:
    metallb.io/allow-shared-ip: technitium
    metallb.io/loadBalancerIPs: "{{LB_DNS_ADDRESS}}"
spec:
  selector:
    app.kubernetes.io/instance: technitium
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: technitium-dhcp
  namespace: networking
  annotations:
    metallb.io/allow-shared-ip: technitium
    metallb.io/loadBalancerIPs: "{{LB_DNS_ADDRESS}}"
spec:
  selector:
    app.kubernetes.io/instance: technitium
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: dhcp
      port: 67
      targetPort: 67
      protocol: UDP
---
kind: Service
apiVersion: v1
metadata:
  name: technitium-dashboard
  namespace: networking
spec:
  selector:
    app.kubernetes.io/instance: technitium
  type: ClusterIP
  ports:
    - port: 5380
      targetPort: http
      protocol: TCP
      name: http
