---
vars:
  - clusterSecret:
      name: cluster-secrets
      namespace: default
      key: SECRET_DOMAIN
      targetPath: SECRET_DOMAIN
  - clusterSecret:
      name: cluster-secrets
      namespace: default
      key: DISCORD_WEBHOOK_URL
      targetPath: DISCORD_WEBHOOK_URL

deployments:
  - path: victoria-metrics
  - path: vmagent
  - path: alertmanager
  - path: vmalert
  - path: grafana
  - path: kube-prometheus-stack
  - path: uptime-kuma
  - path: maintenant
