---
vars:
  - targetPath: SECRET_DOMAIN
    clusterSecret:
      name: cluster-secrets
      namespace: default
      key: SECRET_DOMAIN
  - targetPath: SECRET_EMAIL
    clusterSecret:
      name: cluster-secrets
      namespace: default
      key: SECRET_EMAIL

deployments:
  - path: cert-manager
  - path: cert-manager-webhook-ovh
