---
config:
  global:
    resolve_timeout: 5m
  receivers:
    - name: discord
      discord_configs:
        - webhook_url: "{{DISCORD_WEBHOOK_URL}}"
          title: |-
            {% raw %}[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}{% endraw %}
          message: |-
            {% raw %}{{ range .Alerts -}}
            **{{ .Annotations.summary }}**
            {{ .Annotations.description }}
            {{ if .Labels.pod }}Pod: `{{ .Labels.namespace }}/{{ .Labels.pod }}`{{ else if .Labels.volume }}Volume: `{{ .Labels.volume }}`{{ else if .Labels.node }}Nœud: `{{ .Labels.node }}`{{ else }}Nœud: `{{ .Labels.instance }}`{{ end }}
            Sévérité: `{{ .Labels.severity }}`
            {{ end }}{% endraw %}
  route:
    group_by: ['alertname', 'instance', 'namespace', 'pod']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    receiver: discord

persistence:
  enabled: true
  storageClass: longhorn
  size: 50Mi

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi
