apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-discord
    namespace: monitoring
stringData:
    alertmanager.yml: ENC[AES256_GCM,data:xYvFeH1B3+2bww97L+hqZDj750wOV0U8mOYjTy7smK10iApVgHNo8kaRnVHogptfls0yncXU2ML0v5cK7ul3Rzzzy3G/UrMQLhiWy4ovsCu2kEojqqRNj2I7tbw2avkiWjpFUfdcnwsslyq6c+zX33hW6g7Q9q/BTpHm/P/7F/mIAneSYcuj+gRrhaG6/YSX4I9t2Ur9Ctuz6SCSThcW9le+Y1kIobftlOyeCcGj+vvImGpe7IT7wcAOUg0rxSaVG9Rm4LQs9nt4FaYBUHig0NKv2Bj0gb+2BLtZcQwFJVxtDMmu5IrhtSNP0K7i0pyIgwXMpNYn+62+kMdJLq1MAJeyxzxub9093hatbtYjHXaeg9Ae09ABheQekL6GTUk2LI47OTrYpWxOwhXnoF5L6MJBIke0nn9iDocds29M2pIkRiaG6f/IJN7wkSG1g25wkPYr5tsX2s50rqtqp2uMUBFIekipRVxY37GDYAPqgBkgCDGBJSfz/XqwPHjxfcl9Q6kDLQeDTJ0vtzOWhSczQCYjbWPFJqc1Zo6Z/XgbWGJRat4v3zXtsvxOTwhNWztvXCxu5DLVgvNOlxHppiO9sNuTYbFIuhmKdu3cg4qTZQ2U5UXHWP3dgpTAXj5N7wgPG/qa14JAa/Tj3rYHm9aQBwohZO3/P920E2GE4bFDHPE1OsfRpJ3pNZWaZLRUyyfOmIija1LLiTWXqQoAnTjwqC5djA50SJMy4ePNt/P7HudwWInHjTgbf807qF16UxU3hKQmZYi0Yvltgi/bQaoePEyV+1hQ7LrXalMM88E98mncrUr0ZlkE/4J9EBUnID8t3x31LU5H521qF5ivz4GbDjCkx9MKEOEmuLD7FmNQ5jb4x/cRS8Er27AorMJB+hQkQYuVtAxmEkACVm+H1NHxP/4vAsl8BY9Dt2V4WgEq78kXb5fdtyf6yZqq9qGyaMABPtvWhWF0+e7AiDbgEqFEx/LzrkI=,iv:nwQbvgaOkXO6KmdL+CIRSAtYI+H69m29qniWqARv6Wc=,tag:heAyMkbhJHBVhyUg9m7k3A==,type:str]
sops:
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMHRUYzdSbk1OTkJTelhl
            TEhwL1ZOTytDVC9xWkhFQzc1VGd0ZzdFYzBjCmhqUzMxVTQxb1JVSHBJcGk0Y3VV
            eWtQSmtFVXhwVCthL1diU3E0cWdjVzgKLS0tIHNCZ3RPRmxWaGQxTDMzSnZYMVBr
            Mk94Wkw0VEN5U3FBcHJqWDY4N1lWSzgKjTDMwlu/C3FCKQX7+e24EWeEJkl2a+RF
            7FJUtikCGWgqKzFtxneFtHGBw2xCdDuk/jKHuXRdG8rAT4sUNq2stQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T20:31:26Z"
    mac: ENC[AES256_GCM,data:etspdpKBQ8kRCFAfWMidJ/zGEmXkhyujJkKh12AqqCUnz+JbAigV+GPQ9pySwPYSsIz6OYmBlRkYtRNYJJZGwkUpJwFjOMmiq1SdKjPcELtcjL2BcAfXH210oCQWYaU2w91dQ1SVxaU6BrtD04W7Yy6adPLzXVhN904q/qlqb1g=,iv:cTuJfwdKstUUmtZtLJo4RvCeCSIJs2y6LocwX6a6xD8=,tag:oHyRRfyBaiKSYQYDWd6sIw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
